### ISSUE TITLE
"czyja sprawa" w dodaj sprawę - nie można usunąć wpisanej wartości

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/small_eod#1]
Jak dodaję, czyja sprawa (czy SOWP czy klienta), to po wpisaniu wartości nie mogę jej usunąć (próbowałam esc, delete i backspace):

![image](https://user-images.githubusercontent.com/36925935/41379861-6fc4f622-6f63-11e8-9389-1ac58d787695.png)

Czy jest opcja usuwania?

**Comment by ad-m** [comment]
Kliknij CTRL i możesz swobodnie zaznaczać. Przynajmniej u mnie to działa. Zerkałem jak to zmienić, aby wygodniej się wybierało, ale jeszcze raz zerknę jak to zrobić niskim kosztem.

**Comment by ad-m** [comment]
Zmieniłem sposób zaznaczania na checkboxy.
