### ISSUE TITLE
prośba o powiększenie liczby dopuszczalnych znaków w nazwie załącznika

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/small_eod#10]
Teraz, jak wgrywamy załącznik, to on może mieć maksymalnie 100 znaków, a zdarza się, że jednak pliki mają trochę więcej znaków. Czy można zwiększyć liczbę znaków do 130?

**Comment by ad-m** [comment]
O, super dla wolontariusza ;-)

**Comment by AgnieszkaZdanowicz** [comment]
Już wyjaśniam, o co mi chodzi.

Wchodzę w listy w small-eod i wybieram "dodaj list":

![image](https://user-images.githubusercontent.com/36925935/50685380-3fac6400-1019-11e9-82a0-a184a03f5c3e.png)

I tutaj wrzucam plik (skan pisma, które wgrywam do systemu):

![image](https://user-images.githubusercontent.com/36925935/50685404-5eaaf600-1019-11e9-9a60-58bf4013e470.png)

Jeśli nazwa pliku ma ponad 100 znaków, to pojawia się informacja o błędzie:

![image](https://user-images.githubusercontent.com/36925935/50685470-a03ba100-1019-11e9-93cd-2fc3fa7d17b4.png)

Limit znaków w nazwie pliku jest 100, a fajnie jakby był dłuższy, nawet 150 znaków.

**Comment by ad-m** [comment]
Ups. To oznacza, że wcześniej przygotowany pull request przez wolontariusza zmierzał w dobrym kierunku, a ja zmyliłem.

**Comment by AgnieszkaZdanowicz** [comment]
Sorry, będę opisywać dokładniej

**Comment by AgnieszkaZdanowicz** [comment]
hej, czy ta zmiana będzie robiona jakoś w najbliższej przyszłości? ułatwiłoby nam to pracę, dlatego dopytuję

**Comment by Radek198** [comment]
oj, przepraszam myslałem, że ta zmiana już poszła. Już wysyłam

**Comment by AgnieszkaZdanowicz** [comment]
dzięki :)
