### ISSUE TITLE
subendpointy cases - /case/{caseId}/notifiedUser/* i /case/{caseId}/responsibleUser/*

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#112]

**Comment by ad-m** [comment]
Albo jak collection, albo https://chibisov.github.io/drf-extensions/docs/#nested-routes wygląda ciekawie.

**Comment by silv3rmat** [comment]
DRF-Extensions nie sa przetestowane dla django 3.0. Czy podejmujemy ryzyko problemow z kompatybilnoscia?

**Comment by silv3rmat** [comment]
> DRF-Extensions nie sa przetestowane dla django 3.0. Czy podejmujemy ryzyko problemow z kompatybilnoscia?

Zreszta DRF-nested-routers tez. Poeksperymentuje
