### ISSUE TITLE
subendpointy collection - /collection/*/case/*/{event,letter,note}

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#113]
Zwracam uwagę na szczególne formy uwierzytelniania w ```/collection/*/case/*/{event,letter,note}```.

**Comment by ad-m** [comment]
@matiuszka , uwzględniając rozpiętość czasową pracy nad #184, która po części wynika z konieczności integracji dwóch system, uwzględniając, że #97 również wymaga takiej integracji (i to protokoły z większą ilością zmiennych), może zechcesz zwrócić uwagę na to zagadnienie?

Założenia kolekcji zostały wyjaśnione w https://github.com/watchdogpolska/small_eod/blob/dev/docs/README.md#kolekcja . Implementacja odczytu danych została wykonana w https://github.com/watchdogpolska/small_eod/commit/b11fe9b185ef60957cde9a145d46b682ab324ee9 .

Pozostało wprowadzenie mechanizmu dostępu do informacji (odczytu) z wykorzystaniem innej formy uwierzytelniania niż konto użytkownika. Wymagane jest stworzy tokenu dostępowego, podobny do tego widocznego w GSuite na obrazku:

![image](https://user-images.githubusercontent.com/3618479/74204256-b8e1a600-4c72-11ea-8d58-95632aad5401.png)

W przypadku takich tokenów dostępowych mamy zasadniczo dwie drogi:
- statefull (klasyczne) - zapisanie hasła w bazie danych,
- stateless – wykorzystanie podpisanych certyfikatów umożliwiających dostęp

W tym przypadku myślę, że możemy zacząć od podejścia stateless. Najpopularniejszą drogą w takim  przypadku jest wykorzystanie JSON Web Token ( https://jwt.io/introduction/ ), co w swej istocie jest bardzo podobne do prepodpisanych linków w AWS S3. Token JWT zawiera podpisane cyfrowo (możemy zacząć od kryptografii symetrycznej) dane tj.:
- issuer - wskazanie naszej aplikacji
- subject - wskazanie celu stworzenia podpisu (w tym przypadku identyfikator kolekcji)
- expiration time - czas ważności tokenu

Wymagane jest wprowadzenie endpointu, który pozwoli uwierzytelnionym użytkownikom podpisanego przez serwer tokenu JWT. Implementacyjnie to będzie standardowa akcja wykonywana na ViewSets opisane w dokumentacji DRF.

Równoważnie moglibyśmy wykorzystać ```django.core.signing.TimestampSigner```, ale traktuje, że jest to rozwiązanie legacy ze względu na okres kiedy powstało i posiada pewne istotne ograniczenia (albo podpis nieokreślony czasem albo podpis określony czasem, a nie wymiennie jak dopuszcza to JWT). 

W przypadku, gdy będziemy mieli jakiś token (niezależnie czy statefull lub stateless) potrzebujemy możliwość pominięcia standardowych mechanizmów uwierzytelniania na rzecz wykorzystania – przekazanych przez użytkownika – tokenów dostępowych. Informacje w tym zakresie są dostępne na https://www.django-rest-framework.org/api-guide/authentication/ . 

Uważam, że parametr z tokenem powinien być możliwy do przekazania w nagłówku HTTP (preferowana droga) i jako parametr GET. Odwołuje się w tym zakresie do rekomendacji [Azure](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#75-standard-request-headers) na temat projektowania API:

> For GET and HEAD calls, avoid requiring request headers that are not part of the simple set above. Allow them to be provided as query parameters instead.
> The Authorization header is not part of the simple set, so the authentication token MUST be sent through the "access_token" query parameter instead, for resources requiring authentication. Note that passing authentication tokens in the URL is not recommended, because it can lead to the token getting recorded in server logs and exposed to anyone with access to those logs. Services that accept authentication tokens through the URL MUST take steps to mitigate the security risks, such as using short-lived authentication tokens, suppressing the auth token from getting logged, and controlling access to server logs.

W zakresie dokumentacji zwracam uwagę na następującą sekcje dokumentacji OpenAPI: https://swagger.io/docs/specification/authentication/api-keys/

To będzie także pewien krok dla Ciebie w kierunku #184 , gdyż w OpenID Connect wykorzystywane są tokeny JWT, a jak poznasz JWT to będzie Ci się w przyszłości łatwiej w tym obszarze poruszać.

Kluczowe kryteria sukcesu:

- [ ] dodanie endpointu, który umożliwia otrzymanie tokenu dla kolekcji,
- [ ] dodanie obsługi nowego tokenu,
- [ ] test, który umożliwia pobranie tokenu, a następnie użycie względem API w celu pobrania kolekcji,
- [ ] test, który umożliwia zweryfikowanie, że wygasły token jest odrzucany,
- [ ] test, który umożliwia zweryfikowanie, że nieprawidłowy token jest odrzucany,
- [ ] test, który umożliwia zweryfikowanie, że nie zostały naruszone dotychczasowe formy uwierzytelniania
- [ ] udokumentowanie w dokumentacji API nowej akcji na kolekcji umożliwiającej pobranie tokenu,
- [ ] udokumentowanie w dokumentacji API nowego parametru

**Comment by ad-m** [comment]
Uzmysłowiłem sobie, że powinniśmy w tokenie zamieścić także informacje o identyfikatorze użytkownika na żądanie, którego token został wygenerowany.

**Comment by matiuszka** [comment]
Będę miał na uwadze punktu z tego issue przy implementacji #97

**Comment by matiuszka** [comment]
Wstępnie myślałem, by użyć:
https://github.com/davesque/django-rest-framework-simplejwt
Ale muszę teraz sprawdzić czy w łatwy sposób będę mógł dostosować to by token mógł być przekazany jako parametr get.

**Comment by ad-m** [comment]
To zagadnienie na poziomie implementacji jest niezależne od #97. Dotyka podobnych obszarów, ale implementacyjne to dwa osobne zagadnienia.

Podany przez Ciebie link omawia bibliotekę, która wykorzystuje tokeny do logowania na konto użytkownika (identyfikacja i uwierzytelnienie), a my potrzebujemy wykorzystać tokeny, aby umożliwić dostęp użytkownikom anonimowym (autoryzacja). Obawiam się, że nie jest to trafna biblioteka, chociaż niewykluczone, że można ją dostosować. Mam wątpliwość czy warto.

**Comment by ad-m** [comment]
Przemyślałem sprawę wykorzystania GET uwzględniając kierunek rozwoju API GitHub, który porzucił taką formę uwierzytelniania ( https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters ). Myślę, że wystarczy, abyśmy na poziomie API podobnie jak GitHub akceptowali token JWT wyłącznie w nagłówku ```Authorization```. 

Dla użytkownika końcowego token przekazany będzie w URL, ale w odnośniku do front-endu, a nie w odnośniku do API, więc na tym etapie będzie odpowiednia transformacja.

W dalszym ciągu mam wrażenie, że ```django-rest-framework-simplejwt``` realizuje inny element, gdyż dąży do zastąpienia sesji użytkownika i dostępu do przydzielonych dla niego zasobów, a my chcemy wykorzystać token JWT do kontroli dostępu do zasobu. Możesz zainspirować się sposobem implementacji JWT w tej bibliotece, ale karkołomne będzie integrowanie, więc łatwiej zaimplementować samodzielnie odpowiedni interfejs do przyjęcia tokenu ( https://www.django-rest-framework.org/api-guide/authentication/#custom-authentication ) i akcje do stworzenia tokenu ( https://www.django-rest-framework.org/api-guide/viewsets/#marking-extra-actions-for-routing ) z uwzględnieniem takiej struktury API, aby potencjalnie w przyszłości w łatwy sposób wprowadzić statefull API (nie zakładam zmiany, ale możemy tak zaprojektować API, aby taka zmiana była wstecznie kompatybilna, jeżeli się okaże to konieczne).

O projektowaniu API z uwzględnieniem wstecznej kompatybilności: https://cloud.google.com/apis/design/compatibility

**Comment by matiuszka** [comment]
W takim razie w jaki sposób chcemy wykonywać autentykacje na nasze ViewSety, czy to też nie skończy się tokenach JWT ? 

Kiedyś realizowałem taki przypadek, że użytkownik mógł się autentykować za pomocą credentials w bazie lub poprzez LDAP, tak czy inaczej kończyło się to tym, że użytkownik (a bardziej frontend), dostawał access token i refresh token.

Więc myślałem, że OAuth z Google, będzie o bardzo podobny i kończyć się będzie tym samym czyli otrzymaniem tokenów.

**Comment by ad-m** [comment]
Jak rozumiem pytanie z pierwszego komentarza zdezaktualizowało się po drugim komentarzu. Potwierdzam różnice wskazaną w drugim komentarzu, co pisałem wcześniej.
