### ISSUE TITLE
wprowadzenie reguł lintowania zgodnych z fedrowaniem i poradnią

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#114]
Będzie trochę konfliktów, jeżeli ludzie będą pracować równolegle, ale później nie będzie ich mniej.

**Comment by ad-m** [comment]
@bukowa , prowadziłeś w tym zakresie prace. Czy chcesz jeszcze coś zmienić w tym zakresie?

**Comment by bukowa** [comment]
mnie wszystko pasuje, ew. myslalem nad wydluzeniem dlugosci lini, chociaz na telefonach zle sie czyta, ciezko powiedziec

**Comment by ad-m** [comment]
Osiągnięto.
