### ISSUE TITLE
wprowadzenie testów automatycznych dla CollectionSerializer, InstitutionSerializer, LetterSerializer i EventSerializer

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#115]
Wokół encji będzie się więcej dziać, więc będziemy tego potrzebować. Mamy już przykłady w projekcie.

**Comment by silv3rmat** [comment]
Zaczne najpierw od poprawienia serializerow, potem zajme sie testami.

**Comment by silv3rmat** [comment]
Czy moze stworzyc na to nowe Issue?

**Comment by bukowa** [comment]
@silv3rmat możę utworzyć nowy draft pull request, i pracować na nim, wtedy wszyscy będziemy widzieli co się dzieje

**Comment by ad-m** [comment]
Proponuje przyjąć, że zagadnienie to jednostka pracy. Testy potwierdzają czy serializer został wykonany poprawnie. Jeżeli przy pracy nad jednym, że zmiany są konieczne w w innym zakresie to nie ma przeszkód, abyś je także wprowadził. 

Uważaj tylko, aby nie wprowadzić zbyt wielu zmian w ramach jednego PR, bo wówczas będzie czasochłonna recenzja (już tego doświadczyłeś przy pierwszym PR), która hamuje prace innym i powoduje dodatkowe koszty odkodowania zmian. Nie widzę przeszkód, abyś jedno zagadnienie spowodowało kilka PR. Nawet jak będzie to szło model po modelu, albo naprawdę niewielkimi zmianami.

Jeżeli widzisz błąd i nie możesz się nim zając od razu - proponuje utworzyć zagadnienie, a wtedy jest szansa, że ktoś inny to zrobi. Tak jak ja ten PR zrobiłem po prostu widząc problemy na które sam czasu nie mam.

**Comment by ad-m** [comment]
Przyjmuje, że wykonano w serii PR. Przede wszystkim mamy przetestowane ViewSets.
