### ISSUE TITLE
wprowadzenie filtrowania notatek, wydarzeń i listów według sprawy

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#117]
poprzez ogólną listę?

**Comment by kotEustachy** [comment]
mogę podjąć ten task tylko proszę o dokładniejsze wyjaśnienie wizji użyć paczki:
https://simpleisbetterthancomplex.com/tutorial/2016/11/28/how-to-filter-querysets-dynamically.html
jak w opisie czy po prostu rozszerzyć queryset o .filter() i w jaki sposób będą podawane parametry do filtrowania czy chodzi żeby dla danego eventu, listu lub notatki były wyświetlane tylko sprawy powiązane z danym zagadnieniem

**Comment by ad-m** [comment]
W mojej ocenie optymalnie byłoby ten problem rozpatrywać łącznie z #103, aby zapewnić spójny interfejs wewnątrz aplikacji. Jednak dostrzegam, że #103 jest problemem, który wymaga uważnego zaprojektowania (głównie czy używamy djangoql, czy piszemy własne), a jesteśmy w stanie pracować bez #103 (aplikacja w wersji v1 nie posiada takiego mechanizmu, a potrzebujemy co najmniej dogonić v1, aby zastąpić). Jeżeli weźmiemy się pierw za #117 to filtrowanie poprzez podanie w kolejnych parametrach GET właściwości filtrowania (tak działa django-filter) jest dla mnie w porządku. Dostrzegam, że w przyszłości będzie można zastąpić uzupełnić / zastąpić to filtrowanie rozwiązaniem jednolitym z #117 bez przełamywania kompatybilności wstecznej.

W mojej ocenie filtrowanie poprzez rozszerzenie "queryset o .filter()" jest zbyt ograniczone i szybko nas będzie uwierać zarządzanie tym. Z doświadczenia z django-filter wiem, że jak istnieje pomysł takiego filtrowania to django-filter zrobi robotę.

Możliwość wyświetlenia listów, które nie posiadają filtrowania stanowi kluczowy element dla #47, czyli mechanizmu poczekalni. Poczekalnia na poziomie back-endu to nie będzie nic innego jak lista spraw, które nie zostały przypisane do żadnej sprawy. Na poziomie UI będzie to interfejs zoptymalizowany do przypisania do istniejącej / utworzenia nowej sprawy dla listu.

Odnosząc się do tego przewodnika. Nie jest - w mojej ocenie - istotne generowanie dokumentacji HTML dla REST API. Jednak ważne jest, aby te parametry były dokumentacji OpenAPI (zob. #106).

W zakresie kryteriów filtrowania:

- Case - filtrowanie według sprawy to minimum (także filtrowanie dla "None"), pozostałe kryteria pokazane na screenshocie poniżej z obecnego systemu,
- Note - brak w v1, filtrowanie według sprawy i czasie utworzenia (od, do - dowolna data), wyszukiwanie tekstowe po polu "sprawa",
- Event - brak w v1, filtrowanie według sprawy, czasie utworzenia (od, do - dowolna data), czasie wydarzenia (od, do - dowolna data), wyszukiwanie tekstowe po polu "name" i "comment",

Jeżeli któreś z kryteriów filtrowania nie jest jasne - proszę o sygnał.

Sprawa:
![obraz](https://user-images.githubusercontent.com/3618479/72667580-6f0ff200-3a1d-11ea-9284-29286c639c58.png)
