### ISSUE TITLE
zweryfikowanie czy dane użytkownika, który utworzył i zmodyfikował dla wszystkich encji są poprawne

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#119]

**Comment by zephyrus8888** [comment]
To ja poproszę o przydzielenie zadania.

**Comment by ad-m** [comment]
Czy w tym zakresie chcesz jeszcze coś wykonywać?

**Comment by zephyrus8888** [comment]
Tak, w tym tygodniu zakończę temat związany z fabrykami.

**Comment by ad-m** [comment]
Rozwiązano poprzez `AuthorshipViewSetMixin`.
