### ISSUE TITLE
Wprowadzenie verbose_name i help_text w modelu

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#122]
Sprawdziłem nasze aktualne narzędzie do generowania dokumentacji Swagger. Wykorzystuje ono z modelu pole "verbose_name" i "help_text", zatem warto te pola uzupełnić zgodnie z starą dokumentacją swagger ( https://github.com/watchdogpolska/small_eod/blob/master/docs/swagger.yaml ). 

Przykładowo dla pola:
```python
    min_items = models.IntegerField(default=1)
```
otrzymałem:
```json
                "minItems": {
                    "title": "Min items",
                    "type": "integer"
                },
```

Po zmianie pola na:
```python
    min_items = models.IntegerField(default=1, verbose_name="Min items", help_text="XXXXXx")
```
Otrzymałem:
```json
                "minItems": {
                    "title": "Min items",
                    "description": "XXXXXx",
                    "type": "integer"
                },
```

**Comment by efefre** [comment]
@ad-m  Link do starej dokumentacji prowadzi na stronę 404. Możesz podać poprawny link? Zerknę, czy dobrze rozumiem zadanie.

**Comment by ad-m** [comment]
Dokumentacja została przeniesiona na branch "dev" w tej samej ścieżce: https://github.com/watchdogpolska/small_eod/blob/dev/docs/swagger.yaml 

Wizualizacja możliwa poprzez [Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/watchdogpolska/small_eod/dev/docs/swagger.yaml) lub [ReDoc](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/watchdogpolska/small_eod/dev/docs/swagger.yaml). Jednak w tym przypadku proponuje użyć wizualizacji tylko, aby ogarnąć strukturę YAML.

Prawdopodobnie przy okazji dostrzeżesz różnice pomiędzy projektem, a implementacją. Warto przy okazji to wylistować, abyśmy świadomie rozwijali projekt.

Jeżeli zadanie wydaje się proste to naprawdę taki jest. Zajmuje czas, a nie jest ambitne. Jednak ważne w przyszłości dla odbiorców API, gdy już przestaniemy wspierać się projektem, bo uzyskamy pewność, że wszystko z projektu zostało wykonane.

**Comment by efefre** [comment]
@ad-m  jeszcze dopytam, na przykładzie.
1) Mam po lewej stronie dokumentację i np. pole **name** ma opis **Name of case**. To w modelu powinnam to dopisać jako **help_text**? 
2) verbose_name wpisywać po angielsku, czy po polsku? Pytam bo niżej na tym zrzucie przy **createdOn** widzę polską nazwę.
3) Odnośnie zgłaszania różnic pomiędzy projektem, a implementacją. Chodzi o to, że jak w dokumentacji widzę pole **noteCount**, a w modelu go nie ma, to mam założyć zadanie na GitHubie i wpisać, że tego pola nie ma w modelu?
<img width="1185" alt="Zrzut ekranu 2020-01-16 o 20 10 13" src="https://user-images.githubusercontent.com/29001525/72555674-5d074580-389d-11ea-9ed0-d05d48330499.png">

**Comment by ad-m** [comment]
Pole ```noteCount``` jest polem wirtualnym. W takim znaczeniu, że jest liczone na podstawie powiązanych notatek dynamicznie i nie wchodzi w skład modelu Django. Model Django zawiera tylko stałe, trwałe dane zapisane w bazie danych. Potwierdzić istnienie tego pola możesz przez uzyskanie dokumentacji z wykorzystaniem:

```python manage.py generate_swagger```

Albo po uruchomieniu aplikacji pod adresem ```/api/docs```.

Jeszcze nie mam wiedzy jak takie pola dokumentować. Jeżeli także nie masz takiej wiedzy to dla pól ```*count``` (mamy trzy / cztery w całej aplikacji) utwórz osobne zagadnienie i ktoś opracuje sposób dokumentowania ich.

Trudne pytanie o wpisywanie w języku polskim / angielskim. Proponuje wpisywać w języku angielskim po ubraniu tego w gettext (```_```). Przykładowo:
```python
from django.db import models
from django.utils.translation import gettext_lazy as _

class MyThing(models.Model):
    name = models.CharField(help_text=_('This is name'))
```
Szczegóły: https://docs.djangoproject.com/en/3.0/topics/i18n/translation/
Wówczas będziemy mogli szybko zmienić język w przyszłości.

**Comment by efefre** [comment]
Ok. **nonCount** to zły przykład, ale już brak w modelu **createdOn** albo **modifiedOn** powinnam zgłosić?
Myślę, że możesz przypisać to zadanie do mnie.

**Comment by efefre** [comment]
A nie, już widzę. Te pola są z **TimestampUserLogModel** Czyli jest ok. Nic nie trzeba zgłaszać :)

**Comment by ad-m** [comment]
Odnośnie 1. W pierwszej kolejności powinniśmy wypełnić ```verbose_name```, w drugiej ```help_text```. Pierwsze powinno być krótkie, treściwe. Może wykorzystamy to do budowania opisów pól w formularzach? Drugie może być długie i stanowi objaśnienie do pól. Może to będzie pytajnik przy polu w wygenerowanych formularzach?

Możliwe, że projekt dokumentacji OpenAPI ne posługuje się poprawnie ```title``` i ```description```. 

Odnośnie ```modifiedOn``` i ```createdOn``` to w dokumentacji one są ( https://github.com/watchdogpolska/small_eod/blob/4b38a5a924c85b7ea2a83161762b4c37948c6958/docs/swagger.yaml#L1720-L1723 ), jak również w modelu Django za sprawą dziedziczenia ( https://github.com/watchdogpolska/small_eod/blob/4b38a5a924c85b7ea2a83161762b4c37948c6958/backend-project/small_eod/cases/models.py#L17 , https://github.com/watchdogpolska/small_eod/blob/4b38a5a924c85b7ea2a83161762b4c37948c6958/backend-project/small_eod/generic/models.py#L7-L25 ). W modelu Django mamy notacje zgodną z konwencją Python ( https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html ), ale zamieniamy to na camelCase, która jest zgodna z światem JavaScript ( https://github.com/watchdogpolska/small_eod/blob/4b38a5a924c85b7ea2a83161762b4c37948c6958/backend-project/config/settings/base.py#L137-L143 ).

**Comment by efefre** [comment]
No to powalczę z tym.

**Comment by ad-m** [comment]
Czy mogę jakoś pomóc?

**Comment by efefre** [comment]
@ad-m Dzięki, ale jeszcze nie ma takiej potrzeby. Problemem był brak czasu. Dzisiaj chcę do tego usiąść wieczorem :)

**Comment by efefre** [comment]
@ad-m na ten moment zadanie można zamknąć. Wszystkie PR ze zmianami w modelach są już zmergowane.

**Comment by ad-m** [comment]
Świetnie. Czy masz pomysł czym kolejnym chcesz się zająć?

**Comment by efefre** [comment]
Przeglądam listę zadań i prawdę mówiąc, nie bardzo wiem, czym mogę się teraz zająć.

**Comment by mik-laj** [comment]
@ad-m Czy mogę zamknąc ten bilet?
