### ISSUE TITLE
wprowadzenie paginacji

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#124]
Pewnie django-rest-framework ma coś gotowego.

**Comment by kotEustachy** [comment]
https://github.com/watchdogpolska/small_eod/pull/161

**Comment by maciejparol** [comment]
Ma [Dokumentacja](https://www.django-rest-framework.org/api-guide/pagination/#pagination)

**Comment by ad-m** [comment]
@maciejparol , w #161 już pracujemy nad tym. Wprowadzenie takiego rozwiązania wymagało także zaktualizowania testów. Wymaga to także zweryfikowania jaki to ma wpływ na interfejs autogenerowanej biblioteki SDK, czy np. paginacja nie zwraca linków do kolejnych stron, podczas gdy biblioteka oczekuje wartości. Drobiazgi, ale warto to brać pod uwagę, bo planujemy więcej integracji ( https://github.com/watchdogpolska/small_eod/issues?q=is%3Aissue+is%3Aopen+label%3Aintegrations ), bo będziemy repozytorium, do którego różne systemy będą wkładać dokumenty, a inne pobierać.

**Comment by ad-m** [comment]
Wykonane po stronie back-endu. Etykiety wskazują na ograniczenie do back-endu.
