### ISSUE TITLE
> MEDIA_ROOT

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#128]
> MEDIA_ROOT
> Absolute filesystem path to the directory that will hold user-uploaded files.
https://docs.djangoproject.com/en/3.0/ref/settings/

Należy skorzystać z ```BASE_DIR``` określonego powyżej w pliku.

_Originally posted by @ad-m in https://github.com/watchdogpolska/small_eod/pull/126/review_comment/create_

**Comment by kotEustachy** [comment]
in progress

**Comment by ad-m** [comment]
... in #158
