### ISSUE TITLE
dodanie wyboru z listy, a nie wpisywania dowolnego tekstu, w polu "opis" przy liście

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/small_eod#14]
Dotąd umożliwialiśmy wpisywanie dowolnego tekstu, ale jednak chciałabym ustandaryzować treści tam wpisywane, bo potem łatwiej jest wyszukać np. wszystkie wyroki albo decyzje. Prosiłabym, żeby tu można było dodać tylko taki opis, który jest wcześniej dodany do spisu "opisów". Tak jak jet w instytucjach, tagach etc.

**Comment by AgnieszkaZdanowicz** [comment]
Tylko co z tymi opisami, które dotąd wgrałyśmy? One się dodadzą do listy wyboru?

**Comment by ad-m** [comment]
Należy wykonać odpowiednią migracje z wykorzystaniem ```RunPython```. Jest to trochę bardziej skomplikowane niż pozostałe zadania, ale pozwoli Tobie zrozumieć jak działają migracje w Django tak naprawdę. Jeżeli nie masz z tym większego doświadczenia - zadzwoń, omówimy to.

Wartości, które dotąd wprowadzone powinny zostać przeniesione.
