### ISSUE TITLE
ustawienie podstawowego zakresu uprawnień użytkowników "tylko do odczytu"

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/small_eod#15]
Poza 2 osobami, każda kolejna, która ma konto, otrzymuje tylko 2 uprawniania - "can view the case" i "can view the letter". Czy można ustawić jakiś domyślny rodzaj użytkownika, żebym nie musiała za każdym razem klikać tych opcji?

**Comment by ad-m** [comment]
Należy utworzyć nową aplikacje, dodać ją do ```INSTALLED_APPS```, a następnie złapać na signale pre_save na django.contrib.auth.users, aby dodać ```is_staff=True```, a następnie dodać domyślne uprawnienia (```Permission```) na single ```post_save``` (jeżeli tworzony).

**Comment by bukowa** [comment]
Czy to nie przypisze uprawnie kazdemu uzytkownikowi ktory zalozy konto?

**Comment by ad-m** [comment]
@bukowa , a kto może założyć konto? :-)

**Comment by bukowa** [comment]
@ad-m Udalo mi sie zalogowac przez Google na waszej stronie ale nie wiem jak django-allauth to integruje  odnośnie "is_staff" ?

**Comment by ad-m** [comment]
To problem jest w tym miejscu, a nie przy zakładaniu konta. 

Mozemy to rozwiązać przez nadawanie uprawnień jedynie jeżeli domena użytkownika jest nasza, czyli dodatkowy warunek przed nadaniem uprawnień.
