### ISSUE TITLE
vendor dependencies

### ISSUE THREAD

**Issue by bukowa** [watchdogpolska/small_eod#157]

**Comment by ad-m** [comment]
Which one?

**Comment by bukowa** [comment]
Everything. Swoja droga GoLang ma fajny support vendorowania. Mysle ze warto na samym koncu sie tym zajac, biblioteki zawsze moga zniknac albo moze sie w nich pojawic jakis dziwny kod.

**Comment by ad-m** [comment]
W Pythonie rzadko spotykam vendorowanie bibliotek, a przynajmniej w takich projektach. Możemy mieć sumy kontrolne w pip, aby zapobiec dziwnemu kodowi, chociaż to się dopiero rozwija.

**Comment by mik-laj** [comment]
Ja proponuje pobrać biblioteki i trzymać ich kopie w repozytorium. W ten sposób możemy zainstalować nawet, gdy biblioteka zostanie skasowana z pip. Osobiście jednak nie uważam, że to duży problem.

**Comment by magul** [comment]
Szczerze to nie mam doświadczenia z wendorowaniem bibliotek - prócz kilku wyjątków zawsze ściągaliśmy zależności z publicznie dostępnych rejestrów (a wyjątki przeważnie opierały się na instalacji niedostępnych publicznie, rozwijanych wewnętrznie bibliotek).

Jedyna sytuacja, której bym się obawiał opierając się na publicznie dostępnych rejestrach to faktycznie usunięcie biblioteki z `PyPi` czy z `npm` (tu jeszcze z perspetkywy tego, że korzystamy z Dockera, to powinniśmy gdzieś utrzymywać kopie obrazów z DockerHuba).

Ja bym obecnie był za zamknięciem tego ticketa, bo (jak napisał @mik-laj i też tak uważam) to nie jest duży problem, za to z perspektywy konkretnie naszego projektu myślę, że zbudowanie dodatkowego rozwiązania (lub wielu rozwiązań, bo jednak musielibyśmy tutaj rozmawiać o `npm`, `PyPi` i `DockerHub`) oraz późniejsze jego otrzymywanie będzie powodować większe problemy niż chwilowa niedostępność konkretnej zależności w publicznych rejestrach.

(Pamiętajmy, że jednak pracujemy po godzinach, prezentujemy różne poziomy doświadczeń - w tym jest kilka osób zaczynających przygodę z programowaniem, znacząco łatwiej i szybciej jest wykonać `yarn add` i skomitować zależność, niż utrzymywać całe `node_modules/` w gicie, dodatkowe pytanie brzmi jak ten @renovate-bot by sobie z tym radził, pewnie musielibyśmy z niego zrezygnować).

**Comment by magul** [comment]
Dodatkowo wydaje mi się, że to miałoby sens pewnie gdybyśmy mieli zasoby (ludzkie) by czytać zawartość wszystkich zależności, a to raczej oczywiste, że ich nie mamy.

**Comment by magul** [comment]
Jeszcze jedna sprawa - jeżeli już mielibyśmy zadbać o odtważalność buildów, to raczej bym był skory spędzić czas nad przechodzeniem z `pip` na `pyenv` albo na `poetry`.

**Comment by kuskoman** [comment]
W ramach "nie znam się ale się wypowiem" powiem, że uważam po prostu przechowywanie obrazów dockera do iluś wersji wstecz za (moim zdaniem) wystarczające rozwiązanie.
Poza tym zgaduję, że vendorowanie frontendu mogłoby spowodować kolejne problemy związane z niezgodnością platform
