### ISSUE TITLE
ustawienie filtrów w "sprawach"

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/small_eod#16]
Fajnie, jakby dało się jeszcze filtrować po: "kontrolowana instytucja" Natomiast "Tagi instytucji poprzez listy" można wywalić, bo tagi już dajemy tylko przy sprawach

**Comment by AgnieszkaZdanowicz** [comment]
I jeszcze w sprawach są do zaptaszkowania są takie pola "czyja sprawa", "jaki zakres sprawy", "bezczynność w jakim zakresie" etc. To jakby dało się filtrować po tych polach (aż do "status"), to byłoby super :)

**Comment by ad-m** [comment]
Tylko edycja listy z filtrami. Powinno być trywialne w wykonaniu.

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , wdrożone. Dalsze uwagi do @Radek198 .

**Comment by AgnieszkaZdanowicz** [comment]
Dziękuję, bardzo nam się przyda do podsumowań :)
