### ISSUE TITLE
ogranicznie liczby zapytań w przypadku widoku szczegółowego i listy w ViewSets

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#163]
Wystarczy wykorzystać [self.assertNumQueriesLessThan](https://django-test-plus.readthedocs.io/en/latest/low_query_counts.html#assertnumquerieslessthan-number-context) i rozszerzyć generyczny mixin.

**Comment by fivelamps** [comment]
proszę o przydzielenie zadania

**Comment by ad-m** [comment]
Czy potrzebujesz z mojej strony czegoś w tym zakresie?

**Comment by fivelamps** [comment]
Jeszcze nie wiem, to będzie moje pierwsze zadanie, będę się zgłaszać z
ewentualnymi pytaniami.
Pozdrawiam,
Magda

pt., 3 kwi 2020 o 14:28 Adam Dobrawy <notifications@github.com> napisał(a):

**Comment by fivelamps** [comment]
Co oznacza dodanie do backlog? W ten weekend chciałabym robić pull request.

**Comment by ad-m** [comment]
Zadanie oczekujące na wykonanie. PR are welcome.

**Comment by magul** [comment]
@fivelamps cześć! My zaczęśliśmy sie zdzwaniać co 2 środę, by pogadać o postępach w projekcie, jakbyś chciał brać udział w tych callach, to chętnie zapraszamy!

Dodatkowo zaczęliśmy sobei wizualizować postęp prac na tablicy kanbanowej https://github.com/watchdogpolska/small_eod/projects/1. Zapewne błędnie założyłem, że skoro się nie odzywasz od początku kwietnia, to ticket czeka nadal na wykonianie. Poprawiłem swój błąd i wrzuciłem ticket do kolumny **In progress**. 

To czekamy na pull request i jakbyś chciał(a) zjawić się na tym callu, to zapraszamy!

**Comment by ad-m** [comment]
Prace trwają w #487  .
