### ISSUE TITLE
podstawowy layout UI

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#165]
Wykorzystajmy Ant-Design, aby ograniczyć nakład pracy.

Potrzebujemy:
- sidebar
- pole dla treści zmienianej
- stopkę (link do API, wskaźnik wersji z odesłaniem do GitHub)

**Comment by magul** [comment]
Wydaje mi się, że podstawowy layout obecnie istnieje (Ant Design Pro dostarcza to z definicji).

Stopkę ogarniemy w #326
Na sidebar i polę treści istnieje #166, który za chwilę zacznę rozpisywać na mniejsze tickety.
