### ISSUE TITLE
Pole treści dla listy listów, spraw

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#168]
Potrzebujemy wykaz listów i spraw, a także reszty encji. To obecnie jest tabela:

![obraz](https://user-images.githubusercontent.com/3618479/72554001-2419a180-389a-11ea-8702-2ea7ad3a4a7b.png)

Zwracam uwagę, że w przyszłości będziemy potrzebować wprowadzić filtrowanie rozbudowane.

Na początek możemy zacząć od https://ant.design/components/list/ .

**Comment by SmietankowyImperator** [comment]
Cześć, robię porządki w backlogu, 

@ad-m czy to nie jest duplikat (po części) #386 
Lista spraw została dostarczona w #403 a Lista listów w #359 

Czy ten issue jest do zamknięcia? Filtrowanie i sortowanie ogarniemy w osobnych ticketach.
