### ISSUE TITLE
zmiana szerokości kolumn w tabeli w widoku "listy"

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/small_eod#17]
Wygląda to tak:

![image](https://user-images.githubusercontent.com/36925935/49396300-19a15480-f739-11e8-9c07-84f24b39ca5d.png)

Czy mogą być węższe kolumny "instytucja", "data wysłania/odbioru", a szerszy "komentarz"?

**Comment by AgnieszkaZdanowicz** [comment]
Czy jest szansa, że ktoś w najbliższym czasie się zajmie tą sprawą? :)

**Comment by AgnieszkaZdanowicz** [comment]
Adamie, nie wiem, co tu oznacza Twój komentarz, ale nie widzę zmiany w systemie. Czy Ty mógłbyś się tym zająć?

**Comment by ad-m** [comment]
Wykonane?

**Comment by AgnieszkaZdanowicz** [comment]
Tak i może z tego właśnie powodu nie widać kolejnych kolumn. Ale już trudno, zamykam
