### ISSUE TITLE
Panel użytkownika

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#176]

**Comment by magul** [comment]
@ad-m jesteś może w stanie doprecyzować, czego tutaj ticket dotyczy? Nie mamy tego już dostarczonego (jako duplikat #165)?

**Comment by ad-m** [comment]
Przypuszczalnie miała to być podstawowa zakładka z listą użytkowników lub tylko własnym profilem. Jednak obecnie skłaniam się ku temu, aby starać się tak długo jak to możliwe nie wprowadzać żadnego zarządzania użytkownikami, ani ich uprawnieniami, a spróbować wszystko pobierać z zewnątrz.
