### ISSUE TITLE
zmiana szerokości kolumn w tabeli w widoku "sprawy"

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/small_eod#18]
Czy w tej tabeli może być węższa kolumna "kontrolowana instytucja", a szersza "komentarz"?

**Comment by AgnieszkaZdanowicz** [comment]
Adamie, czy Ty dasz radę wprowadzić tę zmianę?

**Comment by ad-m** [comment]
Niestety, brakuje mi umiejętności w zakresie CSS, aby wprowadzić zmianę (zazwyczaj robił to Kamil). W zakresie Django przystosowałem i muszę tylko złapać kogoś kto drobną zmianę w stylach opracuje, ale samemu nie jestem w stanie, bo kolumny nie układają się tak jakbym chciał. Analogicznie #17 .

**Comment by AgnieszkaZdanowicz** [comment]
A może Marcin Bójko ma takie umiejętności?

**Comment by ad-m** [comment]
Nie wiem, wystarczy, aby uruchomił small_eod, następnie konsole deweloperską, dostosował style, podał mi je, a będą sprowadzone.

**Comment by mrbojko** [comment]
@ad-m w nagłówku strony jest kod CSS wrzucany inline:
```
 <style>
        .column-institution, .field-institution {
            width: 5%;
            word-wrap: break-word;
        }

        .column-data, .field-data {
            width: 5%;
            word-wrap: break-word;
        }

        .column-comment, .field-comment {
            width: 100%;
        }

        table.grp-table {
            table-layout: fixed;
        }
    </style>
```
Trzeba to zamienić na 
```
    <style>
        .column-institution, .field-institution 
		{
            max-width: 300px;
            word-wrap: break-word;
        }

        .column-data, .field-data 
		{
            max-width: 250px;
            word-wrap: break-word;
        }

        .column-comment, .field-comment 
		{
            min-width: 350px;
        }

        table.grp-table 
		{
            table-layout: fixed;
        }
		.column-link_to_case 
		{
			min-width: 350px;
		}		
		.sortable.column-data.sorted.descending 
		{
			max-width: 170px;
		}
    </style>
```
A najlepiej byłoby wstawić to do oddzielnego pliku CSS.

**Comment by mrbojko** [comment]
@ad-m Agnieszka prosiła, żeby poprawić również szerokości kolumn w tabeli: [https://small-eod.siecobywatelska.pl/admin/cases/case/](https://small-eod.siecobywatelska.pl/admin/cases/case/)
Tutaj skrypt niepotrzebnie wrzuca w znacznik <td> klasę _nowarp_ `<td class="field-audited_institution nowrap">Centrum Egzaminów Medycznych w Łodzi</td>`
a oprócz tego w CSS powinno znaleźć się:
`.field-audited_institution 
{
    max-width: 150px;
}`
Sugeruję zrobienie wspólnego pliku tables.css i wrzucenie wpisów z obydwu postów.
Jeśli z jakiegoś powodu usunięcie nowarp byłoby trudne można to obejść redefinicją klasy nowarp, albo całej klasy field-audited_institution.nowrap, ale to niezbyt eleganckie rozwiązanie i lepiej stosować w ostateczności.

**Comment by AgnieszkaZdanowicz** [comment]
Adamie, zaimplementujesz te zmiany?

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz tak
