### ISSUE TITLE
sortowanie w sprawach po "listy"

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/small_eod#19]
![image](https://user-images.githubusercontent.com/36925935/49396832-5f125180-f73a-11e8-9de0-6ab9a7500a4b.png)

teraz nie można sortować po ostatniej kolumnie tj. po "listach".A mi by się to przydało, żebym mogła łatwo zobaczyć, które sprawy musimy jeszcze uzupełnić

**Comment by ad-m** [comment]
To jest dynamiczne pole bazujące na danych w polu z agregacji. Django-admin pozwala sortować po polach w agregacjach, jeżeli na funkcji z dynamicznym polem określi się pole z agregacji . Jeżeli nie znajdziesz tego sprawnie - daj znać, a odszukam w dokumentacji.

**Comment by ad-m** [comment]
https://stackoverflow.com/questions/45921192/django-admin-sort-with-custom-function
