### ISSUE TITLE
prośba o zmianę w sortowaniu, filitrowaniu i widoku tabelki przy listach

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/small_eod#2]
Mam prośbę o zmianę w tej tabelce:

![image](https://user-images.githubusercontent.com/36925935/41604546-cc87dfd4-73df-11e8-8ba7-7a6341efe7cb.png)

Chciałabym, żeby można było sortować po tagach. Tabelka wyszła duża i zastanawiałam się, co można z niej ukryć i w sumie wyszło, że nie musi być widoczny komentarz, utworzono i zmodyfikowano.

I jeszcze, żeby można było filtrować po sygnaturze :)

**Comment by ad-m** [comment]
Sortować po tagach? W jaki sposób? 

Komentarz jest wentylem, który pozwala Wam przechowywać dowolne wartości. Przemyśl czy chcesz go utracić.

Utworzono i zmodyfikowano skoro nie jest dla Was użyteczne ukryje.

**Comment by AgnieszkaZdanowicz** [comment]
Ale ja nie chcę kasować komentarza, tylko nie chcę, żeby był widoczny w tabelce, bo tam już za dużo danych się wyświetla.

A sortować po tagach bym chciała, bo tagi w listach to są nazwy monitoringów np. "nagrody" i chciałabym, żeby można było przesortować (znaczy kliknąć w nagłówek "tag" i żeby układało się alfabetycznie), żeby można było zobaczyć ułożone po kolei wszystkie listy oznaczone tym tagiem. Mogę Ci to wyjaśnić w piątek

**Comment by ad-m** [comment]
Ok, porozmawiamy o tych tagach, bo musisz precyzyjnie określić co chodzi, bo tagów masz wiele dla jednej sprawy i muszę jakoś wybrać tag wiodący, bo przecież po wielu wartościach sortować się nie da.
