### ISSUE TITLE
Literówka w Event

### ISSUE THREAD

**Issue by efefre** [watchdogpolska/small_eod#234]
W nazwie pola jest literówka. Rozumiem, że trzymamy się angielskich nazw, więc raczej **date**, a nie **data**.

```
class Event(TimestampUserLogModel):
    data = models.DateTimeField(verbose_name=_("Date"), help_text=_("Date of event."))
```

**Comment by ad-m** [comment]
Czy to jest jedyna różnica między projektem API, a jego implementacją?

**Comment by efefre** [comment]
To jest jedyna różnica jaką zauważyłam przy sprawdzaniu verbose_name i help_text :)

**Comment by ad-m** [comment]
A strukturę danych i endpointy porównywałaś także? 

To nie jest zawarte w help_text ani w verbose_name ;-)

**Comment by efefre** [comment]
Sprawdzałam, gdzie był używany Event i **data** zamiast **date** i tam poprawiałam.
Wyszły mi trzy pliki, które są w PR.

**Comment by ad-m** [comment]
#235
