### ISSUE TITLE
Zmiana nazwy pól na liczby mnogie

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#256]
Zagadnienie zainicjowane w  #249 przez @magul

Tak jak wskazywałem, jestem otwarty co do zmiany na liczbę mnogą i przyjmuje to już jako zadanie do wykonania. Dostrzegam, że będzie to miało potencjalnie duży wpływ na API postaram się, aby do końca tygodnia zostało zamknięte.

**Comment by magul** [comment]
Myślę, że możemy to po prostu rozpisać i powoli realizować. Myślę, że @hkaczmarek90 chętnie sukcesywnie będzie to ogarniał.

**Comment by ad-m** [comment]
Zmiana jest rozległa, ale nie złożona techniczna. To jest jej wyzwanie, ale także szansa, aby zapoznać się z całym projektem i zrozumieć jeszcze bez dużych wyzwań technicznych. Wieczorem rozpiszę to na osobne zagadnienie per moduł.

**Comment by ad-m** [comment]
Stworzyłem oddzielne zagadnienia, aby – mam nadzieje – łatwiej organizować zadania.

W każdym przypadku schemat będzie identyczny:

- aktualizacja pól w modelu,
- dodanie migracji i jej wykonanie,
- aktualizacja pól w serializatorze i jego metodach,
- aktualizacja testów, aby przechodziły poprawnie,
- weryfikacja dokumentacja OpenAPI

Niewykluczone, że w niektórych modułów nie będzie miało to zastosowania, więc będzie można szybko zamknąć.

**Comment by magul** [comment]
Temat zrealizowany. Issue zamykam.
