### ISSUE TITLE
Zmiana nazwy pól na liczby mnogie - administrative_units

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#261]
Podzadanie dla #256

**Comment by hkaczmarek90** [comment]
Tutaj akurat models.py jest puste. Do zamknięcia?

**Comment by ad-m** [comment]
Tak, model będzie pochodził z aplikacji ```django-teryt-tree```, więc po stronie naszej aplikacji będziemy mieli tylko viewsets, co jest w zakresie #120
