### ISSUE TITLE
Zmiana nazwy pól na liczby mnogie - cases

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#262]
AC1. Trzeba rewertować zmianę z #299 dotyczącą `comment(s)`. Zarówno obecna wersja (z brancha `master`) jak i sama definicja modelu pokazuje, że `comment` występuje w liczbie pojedynczej (tam jest tylko `CharField`, nie jest to kolekcja komentarzy).
AC2. Poprawić semantyczność `related_names` dla kluczy `notified_users` i `responsible_users`. Standardowo _Django_ ustawia tę wartość jako `<liczba_pojedyncza_releated_name>_set` (czyli jeżeli mamy w modelu `Case` atrybut `audited_institutions` to wychodząc od strony modelu `Institution` wszystkie sprawy dotyczące danej instytucji możemy wyciągnąć jako:
```
institution = Institution.objects.get(...) # tutaj wyciągamy pojedynczy obiekt instytucji
cases = institution.case_set.all() # tutaj wyciągamy queryset zawierający wszystkie sprawy przypięte do danej instytucji
```
). W sytuacji, gdy do tego samego modelu mamy dwa klucze, to _Django_ nie radzi sobie z nazywaniem odwrotnego linkowania, przez co musimy podać je explicite. Tutaj pewnie bym proponował (przy zachowaniu konwencji `..._set`) ustawienie tych `related_name` na `notified_about_case_set` i `responsible_for_case_set`. Przy czym tutaj chętnie usłyszę jakieś inne propozycje.
AC3. Odpowiednia aktualizacja migracji, faktorek i serializerów.
AC4. Zadbadnie o odświeżenie SDK (zarówno SDK samego w sobie jak i wersji zainstalowanej w aplikacji frontedowej).

Do dalszego czytania:
 * [ForeignKey.related_name](https://docs.djangoproject.com/en/3.0/ref/models/fields/#django.db.models.ForeignKey.related_name)
* [Following relationships “backward”](https://docs.djangoproject.com/en/3.0/topics/db/queries/#backwards-related-objects )

Podzadanie dla #256

**Comment by hkaczmarek90** [comment]
Biorę jako pierwsze do zrobienia

**Comment by ad-m** [comment]
W #256 jest plan działania z tym obszarem. Czy wiesz jak do tego zagadnienia podejść? Gdzie widzisz wyzwanie?

**Comment by hkaczmarek90** [comment]
Wykonane w #299

**Comment by hkaczmarek90** [comment]
Wykonane w #299
