### ISSUE TITLE
Zmiana nazwy pól na liczby mnogie - collections

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#264]
AC1. Trzeba rewertować zmiany z #303 dotyczącą `query/ies` i `comment(s)`. Te atrybuty są zdefiniowane jako `CharField`, co by wskazywało na ich pojedynczość (a nie kolekcję odpowiednio _zapytań_ i _komentarzy_).
AC2. Odpowiednia aktualizacja migracji, faktorek i serializerów.
AC3. Zadbadnie o odświeżenie SDK (zarówno SDK samego w sobie jak i wersji zainstalowanej w aplikacji frontedowej).

Podzadanie dla #256

**Comment by hkaczmarek90** [comment]
Biorę do wykonania

**Comment by hkaczmarek90** [comment]
Wykonane w #303
