### ISSUE TITLE
Zmiana nazwy pól na liczby mnogie - features

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#265]
AC1. Trzeba rewertować zmianę z #307 dotyczącą `feature(s)`. `FeatureOption` powinien być obiektem jednoznacznie przypiętym do pojedynczego `Feature`. Dodatkowo jego definicja wskazuje na `ForeignKey` co oznaczałoby że pod tym atrybutem kryje się pojedynczy obiekt, a nie ich kolekcja.
AC2. Odpowiednia aktualizacja migracji, faktorek i serializerów.
AC3. Zadbadnie o odświeżenie SDK (zarówno SDK samego w sobie jak i wersji zainstalowanej w aplikacji frontedowej).

Podzadanie dla #256

**Comment by hkaczmarek90** [comment]
Brak aplikacji dictionaries ?

**Comment by ad-m** [comment]
Przemianowana na features.

**Comment by hkaczmarek90** [comment]
Biore do wykonania

**Comment by hkaczmarek90** [comment]
Wykonane w #307
