### ISSUE TITLE
Zmiana nazwy pól na liczby mnogie - events

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#266]
AC1. Trzeba rewertować zmiany z #305 dotyczącą `case(s)` i `comment(s)`. `case` jest zdefiniowany jako `ForeignKey`, a `comment` jako `CharField`. W obydwu przypadkach jest to pojedyczny element, a nie ich kolekcja.
AC2. Odpowiednia aktualizacja migracji, faktorek i serializerów.
AC3. Zadbadnie o odświeżenie SDK (zarówno SDK samego w sobie jak i wersji zainstalowanej w aplikacji frontedowej).

Podzadanie dla #256

**Comment by hkaczmarek90** [comment]
Wykonane w #305

**Comment by magul** [comment]
Napisałem komentarz w #305. Gdyby to #305 było poprawnie wykonane, to pewnie możemy ten ticket zamknąć, ale mam dosyć poważne wątpliwości, czy tam za daleko nie popłynęliśmy.

BTW @hkaczmarek90 możesz używać tego, by automatycznie zamykać tickety za pomocą pull requestów: https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
