### ISSUE TITLE
Zmiana nazwy pól na liczby mnogie - files

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#267]
Podzadanie dla #256

**Comment by hkaczmarek90** [comment]
Biorę do wykonania

**Comment by hkaczmarek90** [comment]
Wykonane w #308

**Comment by magul** [comment]
Robię reopen, by nam temat nie uciekł w środę.

**Comment by magul** [comment]
Zamykam, ponieważ w `files.models.File` nie posiada żadnego atrybutu, który wskazywałby na kolekcję (zamiast na pojedynczy obiekt).
