### ISSUE TITLE
Zmiana nazwy pól na liczby mnogie - letters

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#270]
Podzadanie dla #256

**Comment by hkaczmarek90** [comment]
Biorę do wykonania

**Comment by hkaczmarek90** [comment]
Wykonano w #309

**Comment by magul** [comment]
Zamykam, ponieważ w zarówno letters.models.Description` jak i `letters.models.Letter` nie posiada żadnego atrybutu, który wskazywałby na kolekcję (zamiast na pojedynczy obiekt).
