### ISSUE TITLE
wprowadzenie komendy do inicjalizacja bazy danych z losowymi obiektami

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#292]
Kryteria akceptacji:

1. Wykorzystanie django management commands: https://docs.djangoproject.com/en/3.0/howto/custom-management-commands/
2. Wykorzystanie wbudowanych fabryk dostępnych w ```small_eod.*.factories```
3. Szerokie pokrycie testowymi danymi różnych typów treści.

Zwracam uwagę, że factories automatycznie podążają za relacjami.
Na tym momencie nie potrzebujemy żadnych parametrów dla testowych danych.

**Comment by ad-m** [comment]
@qbasuperfly , czy potrzebujesz jakieś pomocy?

**Comment by zephyrus8888** [comment]
Czy ktoś już się tym zajmuje? Jeśli nie proszę o przypisanie.

**Comment by ad-m** [comment]
Weszło w #436 .
