### ISSUE TITLE
mysql encoding

### ISSUE THREAD

**Issue by bukowa** [watchdogpolska/small_eod#30]
Podczas testow otrzymuje:

````python
django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xF4\\x82\\xB4\\x86\\xE4\\x9B...' for column 'password' at row 1")
````
https://stackoverflow.com/questions/10957238/incorrect-string-value-when-trying-to-insert-utf-8-into-mysql-via-jdbc

Probowalem bawic sie kodowaniem ale nic z tego, stary nieszczesny mysql, ktorego nie znam. Czy przejscie na postgres to jakas opcja? Ostatni update pare miesiecy temu, przy czym mysql 5.7 w 2015.
Do tego extra support dla GEO:

https://docs.djangoproject.com/en/2.1/ref/contrib/gis/
https://github.com/djangonauts/django-rest-framework-gis

**Comment by bukowa** [comment]
Obszedlem to przypisujac inne haslo, ale w przyszlosci blad i tak moze sie pojawic/

**Comment by ad-m** [comment]
Mamy inne aplikacje, które są wykorzystują MySQL. Nie mamy potrzeby wykorzystywać GEO. Ze względu na utrzymanie wolałbym uniknąć nowego silnika bazodanowego, który wymaga monitoringu, osobnych procedur backupu, monitoringu backupu, pamięci operacyjnej itd. Obecnie samodzielnie Stowarzyszenie wykorzystuje współdzieloną instancje MySQL i jest to wystarczające.

Przedstawiony błąd można wyeliminować poprzez odpowiednie kodowanie bazy danych. Dotąd nie wystąpił w żadnej produkcyjnej aplikacji Django Stowarzyszenia, a łapiemy wyjątki starannie poprzez Sentry. Zmiana kodowania bazy danych wymaga weryfikacji w zakresie poprawności działania indeksów na polach tekstowych.
