### ISSUE TITLE
rest api

### ISSUE THREAD

**Issue by bukowa** [watchdogpolska/small_eod#31]
Stworzyłem prototyp https://github.com/bukowa/small_eod/tree/restframework
Aby odpalić: 
````
git clone https://github.com/bukowa/small_eod/tree/restframework
docker-compose -f docker-compose-dev.yml up

# testy
docker exec small_eod_web_dev python manage.py test --noinput --keepdb
````

Można wejść na:
http://127.0.0.1:8000/api/docs/swagger/
http://127.0.0.1:8000/api/docs/redocs/

Odczytywanie już w zasadzie działa, ale to tylko prototyp aby zobaczyć jak to wygląda.
Należy stworzyć standard co do tego jak serializować dane. Tworzenie może okazac się troche trudniejsze, ale to zależy od tego co chcemy przekazywać w POST.

![redoc_doc](https://user-images.githubusercontent.com/38087302/50729782-d5daaa00-113f-11e9-8c60-b665bd98f305.png)
![swagger_doc](https://user-images.githubusercontent.com/38087302/50729783-d83d0400-113f-11e9-9e54-e98858666351.png)

**Comment by ad-m** [comment]
Zdecydowanie zgadzam się, że REST API to słuszna droga. Przemyślenia wymaga jednak nowa, szersza struktura danych. Zapraszam do komentowania projektu w https://github.com/watchdogpolska/small_eod/pull/70 .

**Comment by matiuszka** [comment]
Bardzo martwi mnie zagnieżdżanie zasobów. Przykład _letter_list_ spowoduje praktycznie zrzut całej bazy przez API. Może jednak zamiast zagnieżdżać wszytko w dół, lepiej wysyłać PK do innych obiektów ? Lub jakieś hyperlinked API ? Wtedy to frontend będzie decydował co chcę i kiedy.
Albo przynajmniej jakaś paginacja na te widoki list.

**Comment by ad-m** [comment]
Na Slacku omówiliśmy, że ten PR jest nieadekwatny do small_eod V2, gdyż wykorzystuje nieaktualny model, stąd zamykam.

**Comment by bukowa** [comment]
@ad-m jest publiczny slack gdzie kazdy moze wejsc?

**Comment by ad-m** [comment]
@bukowa, SJJ dołączyło do projektu i organizuje współpracę z wolontariuszami wprowadzając Slack. Dziś dyskutowaliśmy, aby dodać link w repozytorium. To jest podobno odnośnik, który umożliwi Ci dostęp, ale ważny przez pewien czas: https://join.slack.com/t/watchdogsii/shared_invite/enQtODY4NjU5MTM4NTYwLTNhNDAyNWViMjg1MWZkMGI3Y2Q1Yjk2MTJlYzg3ZmQ0NWNiMDk4NmM4ZDc1MTU0Yjk4ZmQwYTY4MGQ0NWNkNjQ
