### ISSUE TITLE
Ekran listy spraw

### ISSUE THREAD

**Issue by magul** [watchdogpolska/small_eod#316]
AC1. Ekran spraw powinien być dostępny w menu bocznym pod przyciskiem `Sprawy` (pierwszy element menu, w menu występuje drugi element o nazwie `Sprawy`, ale on zostanie usunięty w osobnym pull requeście).
AC2. Przycisk dodawania sprawy (`Sprawy` > `Nowa`) z menu bocznego zostanie przeniesiony na górę ekranu listy spraw (tak, jak to występuje w _Django Admin_ czy _Grappelli_):
![Screenshot from 2020-05-12 10-40-16](https://user-images.githubusercontent.com/1165138/81661855-053cad80-943d-11ea-970b-8fca6c01d910.png)
AC3. Rząd na liście spraw zawiera:
 * nazwę
 * kontrolowaną instytucję
 * komentarz
 * datę utworzenia
 * datę modyfikacji
 * przypisane tagi
 * licznik listów przypiętych do sprawy
(należy potwierdzić, że SDK wspiera te wartości, w uzasadanionych przypadkach założyć osobne issue na dostarczenie takiej funkcjonalności w Django i później w SDK).
AC4. Paginacja (powinna być dostępna z perspektywy SDK).

Tematy poza tym issue:
 * ekran edycji sprawy,
 * ekran listy spraw przypisanych do sprawy
 * filtorwanie listy spraw

**Comment by mik-laj** [comment]
Ja dopiero w weekend mogę zacząć pracować. Jest.u mnie trochę tłoczno w kalendarzu w tym tygodniu.

**Comment by magul** [comment]
Bez problemu, ja sam w tym tygodniu przymuliłem i dopiero teraz wrzucam tematy.

**Comment by magul** [comment]
Zakładając, że tutaj temat nie ruszył, zamykam jako duplikat #386 (tam chyba jest to teraz lepiej opisane).
