### ISSUE TITLE
Usunięcie relacji 1-to-1 w modelu instytucji

### ISSUE THREAD

**Issue by magul** [watchdogpolska/small_eod#317]
Podczas planowania pracy 06/05/2020 wyszło nam, że nie ma potrzeby utrzymywać w aplikacji Django `institutions` 3 osobnych modeli danych (`AddressData`, `ExternalIdentifier` i `Institution`), ponieważ dwa z nich są połączone w relacji `1-to-1` z trzecim:
```
class Institution(TimestampUserLogModel):
    ...
    address = models.OneToOneField(...)
    external_identifier = models.OneToOneField(...)
```

AC1. Usunąć `AddressData` (sam model jak i połączenie do `Institution`) przenosząc jednocześnie pola z `AddressData` bezpośrednio do modelu `Institution`.
AC1. Usunąć `ExternalIdentifier` (sam model jak i połączenie do `Institution`) przenosząc jednocześnie pola z `ExternalIdentifier` bezpośrednio do modelu `Institution`.
AC3. Uaktualnić faktorki i serializery.
AC4. Zadbać, o odświeżenia SDK (zarówno samego SDK jak i przpięcia do aplikacji frontendowej).

**Comment by ad-m** [comment]
Dlaczego chcesz zaktualizować SDK? Czy struktura API, gdzie te rzeczy są zgrupowane nie jest bardziej przystępna do użycia? API to publiczny interfejs.

**Comment by magul** [comment]
@ad-m w sumie nie zajrzałem, jak wygląda tutaj serializer. W tym AC4 bardziej chodziło mi o to, że jeżeli będzie zmiana w API, to żeby zadbać o odświeżenie SDK w aplikacji frontendowej. W sytuacji połączenia tych tabel w jedną, żeby zachować kształt API, będzie trzeba trochę przepisać serializer (i to też jest coś, na co osoba implementująca zmianę będzie musiała zwrócić uwagę, co w sumie jest tylko i wyłącznie wymogiem AC4, żeby o tym nie zapomnieć).

**Comment by magul** [comment]
Co do zagnieżdżenia adresu i identyfikatora, to nie mam tutaj jakiegoś wyrobionego zdania, jedyne co mi jakoś zgrzyta, to umieszczenie w `address` emaila i epuapu. Tutaj bym rozważył zmianę nazwy na `contact` (bo `address` mi się kojarzy z fizycznym adresem).

Dodatkowo z perspektywy tego zagnieżdżenia może ten ticket nie ma sensu? Może nie powinniśmy się fiksować na spłaczeniu tych modeli?

**Comment by ad-m** [comment]
Ja patrzyłem na to. Zacząłem pracę, ale odpuściłem, bo struktura API jest satysfakcjonująca, a model możemy zmienić. Obecny działa i API jest przetestowane.

**Comment by ad-m** [comment]
W przypadku tego systemu wszelkie dane adresowe są danymi kontaktowymi, więc może powinniśmy pójść raczej w kierunku zmiany address_data w contact. Wówczas będziemy mogli w przyszłości łatwo denormalizować dane (adresy instytucji ulegają zmianom i miło jest zachowywać stary adres po wysłaniu listu), bo po prostu kopiując strukturę contact (z opcjonalnym dostosowaniem przez użytkownika).

**Comment by magul** [comment]
Widzę, że ten temat już poleciał, mnie w każdym razie przekonuje przykład zbierania historii edycji tutaj, zarówno jeżeli chodzi o dane kontaktowe jak i chociażby o nazwę instytucji.

Myślę, że tu byłoby pomyśleć o meta-modelu, który zbierałby wszystkie zmiany z w dowolnym modelu i zapisywał je w osobnej tabeli. Ale to temat obecnie znacząco poza **v2**.

**Comment by ad-m** [comment]
@magul , z mojego doświadczenia wersjonowanie skutecznie rozwiązuje django-reversion, chociaż oczywiście to zależy od wymagań. Nie jest to istotne teraz.
