### ISSUE TITLE
Migracja z JavaScriptu na TypeScript

### ISSUE THREAD

**Issue by magul** [watchdogpolska/small_eod#318]
Zarówno Ant Design Pro jak i React wspiera typowanie zmiennych przy użyciu TypeScripta.

**Comment by kuskoman** [comment]
Celem uporządkowania:
Powiązane PR: #302, #298, #290, #285, #289

**Comment by kuskoman** [comment]
@magul myślę, że issue można uznać za zamknięte, mimo, że na ten moment 323 jest dalej open- w gruncie rzeczy osiągnęliśmy cel i zmigrowaliśmy do ts
