### ISSUE TITLE
Przeniesienie testów e2e do TypeScriptu

### ISSUE THREAD

**Issue by kuskoman** [watchdogpolska/small_eod#320]
Przeniesienie plików z katalogu `e2e` z JavaScriptu do TypeScriptu

Pliki mogą wymagać minimalnej ingerencji poza zmienieniem rozszerzenia pliku.

Podtask dla #318

**Comment by magul** [comment]
@kuskoman @ad-m tutaj jeszcze pytanie, czy my chcemy utrzymywać testy e2e? Pamiętam, że ostatnio @kuskoman pisałeś, że one nie działają. Czy w takim wypadku (skoro jeszcze nie mamy pomysłu jak je uruchamiać) nie lepiej się tematu pozbyć (chociażby tymczasowo)?

**Comment by kuskoman** [comment]
Moja dusza backendowca płacze za każdym razem jak test coverage spada, aczkolwiek możemy spróbować zmienić całą zasadę działania testów
Osobiście wyrzuciłbym ten config Jest i zamiast Jest użył TS-Jest (używam zawsze na backendzie i polecam, lecz nie wiem jak jest z używaniem tego z reactem, postaram się obadać sprawę).
A do puppeteera może być osobny config i testy mogą być nawet w czystym js, wątpię żeby wpłynęło to jakoś na jakość kodu
Wtedy testy byłby podzielone na dwa osobne configi i byłyby uruchamiane z dwóch osobnych komend. 
Co o tym myślicie?

**Comment by magul** [comment]
Ja też wolałbym nie obniżać pokrycia testami. Pytanie, czy to co my teraz w tych testach mamy to jest sensowne pokrycie (pokrycie czego?)? Docelowo, jakbyśmy opracowali sposób uruchamiania tych testów to oczywiście byłbym za ich utrzymaniem (i wtedy prawilnie w TS, bo nie ma powodu by to zostawiać w JS).

Pytanie na chwilę obecną po prostu brzmi, czy to jest coś, co faktycznie przyniesie nam wartość i czy to jest ten moment, że chcemy by to działało. Bo inaczej raczej nie ma sensu trzymać kodu, którego nie wiemy jak uruchomić, który nie działa i nie ma nawet planu, by zaczął działać.

**Comment by kuskoman** [comment]
@magul Co do ts w e2e to próbowałem to zrobić, ale pupeteer nie chciał działać z ts-jest, widziałem paczkę na npmjs, która miała to naprawić, ale sprawdziłem ją i też nie działało.
Testy inne niż e2e powinno się bez problemu.

Spróbuję jeszcze potem [tego sposobu](https://medium.com/better-programming/how-to-use-puppeteer-with-jest-typescript-530a139ffe40), całkiem możliwe, że będzie działać bez problemu, po prostu robiłem to w pierwszym PR, gdzie skupiłem się na dodawaniu TS, więc dałem sobie z tym szybko spokój

**Comment by magul** [comment]
Doszliśmy do porozumienia z @kuskoman i na chwilę obecną zamykam na korzyść #330
