### ISSUE TITLE
Przeniesienie serwisów do TypeScriptu

### ISSUE THREAD

**Issue by kuskoman** [watchdogpolska/small_eod#321]
Podtask dla #318 

Może być utrudniony dopóki https://github.com/watchdogpolska/small-eod-sdk-javascript/issues/3 nie zostanie rozwiązane

**Comment by magul** [comment]
Tutaj chyba zostało tylko to: https://github.com/watchdogpolska/small_eod/blob/f804ce2c7d7364ed107ac8bfcfa91a508f4c680a/frontend-project/src/services/user.js przy czym pewnie to zamiast przenosić do TypeScripta, to można to zaorać?

**Comment by kuskoman** [comment]
@magul na to wygląda, pytanie tylko czy można to już zaorać bo tak mocki chyba są

**Comment by magul** [comment]
Jak już stworzyłeś #420 na ten konkretnie serwis, to ten task zamykam. Jak się okaże, że o czymś zapomnieliśmy to się stworzy nowe zadanie.
