### ISSUE TITLE
Przeniesienie stron do TypeScriptu

### ISSUE THREAD

**Issue by kuskoman** [watchdogpolska/small_eod#322]
Migracja stron z katalogu `pages` do języka TypeScript

Podtask dla #318

**Comment by kuskoman** [comment]
Z racji bardzo dużej ilości plików w tym katalogu konieczne może okazać się rozbicie tego issue na mniejsze (i oczywiście rozbicie tego taska na co najmniej kilka pull requestów)

**Comment by magul** [comment]
Przeleciałem przez cały drzewo `pages/` i został nam tylko jeden plik do przeniesienia: https://github.com/watchdogpolska/small_eod/blob/f804ce2c7d7364ed107ac8bfcfa91a508f4c680a/frontend-project/src/pages/user/login/index.jsx

**Comment by magul** [comment]
Zamykam to, postęp będziemy śledzić w #419
