### ISSUE TITLE
Implementacja stopki

### ISSUE THREAD

**Issue by magul** [watchdogpolska/small_eod#326]
Stopka powinna zawierać:
 * link do repozytororium na GitHubie
 * link do konkretnego commita na GitHubie (wartość przekazywana jako zmienna środowiskowa podczas budowania assetów frontendowych)
 * link do API (wartość przekazywana jako zmienna środowiskowa podczas budowania assetów frontendowych).

Dodatkowo:
 * trzeba uzależnić konfigurację SDK przy użyciu linku do API
 * rozważyć domyślne wartości podczas uruchamiania aplikacji w trybie deweloperskim.

Podzadanie #165

**Comment by ad-m** [comment]
W podstawowym zakresie zadanie wykonano w #452 ?
