### ISSUE TITLE
Dodanie testów do github workflowu dla frontendu

### ISSUE THREAD

**Issue by kuskoman** [watchdogpolska/small_eod#333]
Dodanie checka przeprowadzającego testy automatyczne dla frontendu do github workflow.

Testy przeprowadza się komendą skryptem `test` (`yarn test`).

**Comment by kuskoman** [comment]
Sugerowałbym przy tym zastąpienie menadżera pakietów npm narzedziem yarn, aby ujednolicić środowisko testowe z developerskim

**Comment by magul** [comment]
> Sugerowałbym przy tym zastąpienie menadżera pakietów npm narzedziem yarn, aby ujednolicić środowisko testowe z developerskim

Jak rozumiem chodzi Tobie o to, co jest uruchamiane tutaj: https://github.com/watchdogpolska/small_eod/blob/ec6ce39fba83583db51110d9d8fca64e06890f25/.github/workflows/javascript.yaml

**Comment by kuskoman** [comment]
Tak, cały workflow proponuję zmienić na używający yarna
Można prawdopodobnie po prostu dodać npm i yarn -g

**Comment by macieklukasik88** [comment]
Zajme sie tym

**Comment by macieklukasik88** [comment]
https://github.com/watchdogpolska/small_eod/pull/551
