### ISSUE TITLE
Wprowadzenie filtrowania instytucji

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#337]
W #335 ukazała się potrzeba pobrania listy instytucji wyszukanych według ogólnych kryteriów. 

Wymagania:

- [ ] lista instytucji winna być rozbudowana o filtrowanie
- [ ] filtrowanie winno brać pod uwagę pole "name"
- [ ] filtrowanie winno być otwarte w przyszłości na wprowadzenie filtrowania po rozbudowanych kryteriach (#103) np. poprzez wykorzystanie ogólnej nazwy pola tj. "query"
- [ ] nowy parametr listy instytucji powinien być udokumentowany w API
- [ ] filtrowanie winno być przetestowane, co najmniej integracyjnie,
- [ ] wielkość liter nie ma znaczenia

CC: @magul

**Comment by ad-m** [comment]
@magul , dlaczego "refine"? Masz uwagi / pytania?

**Comment by magul** [comment]
wrzuciłem do `To refine` bo mam w planach to rozdzilić na część backendową i fronteendową.

**Comment by ad-m** [comment]
W mojej ocenie to zagadnienie dotyczy wyłącznie back-endu (stąd taka etykieta), ale zgadzam się z potrzebą stworzenia zagadnienia dla front-endu.

**Comment by mateuszmagulski** [comment]
Ostatnio chyba była mowa o trzymaniu wszystkich instytucji w store i filtrowaniu po stronie frontendu. Jaki kierunek obieramy?

**Comment by ad-m** [comment]
@mateuszmagulski , w https://github.com/watchdogpolska/small_eod/pull/335 pojawiła się implementacja, która zakładała pobranie wszystkiego, ale moim zdaniem nie jest to trafna droga.

**Comment by mik-laj** [comment]
Ja chętnie węzmę te zadanie.

**Comment by magul** [comment]
@ad-m, to zakładamy, że to dotyczy tylko części backendowej. Po niej pewnie będzie trzeba 'podbić' SDK i użyc tego filtrowania w polu, które uzupełnia @Loczi94 w #335. Dlatego pisałem, że dotyczy dwóch przestrzeni.

Ja myślę, że dopóki to nie zostanie dostarczone to my pewnie zmergujemy (bo widziałem już approve'a od @kuskoman ) ten #335 i później w osobnym issue filtrowanie w tym polu zostanie dostarczone.

**Comment by ad-m** [comment]
@magul , nie widzę problemu, aby wydzielić z #335 noweg zagadnienie nt. dynamiczne filtrowanie po nazwie.

**Comment by ad-m** [comment]
@mik-laj , jaki masz ETA dla tego zagadnienia?

**Comment by mik-laj** [comment]
W piątek/sobote rozpoczynam pracę i nie pójdę spać poki tego nie ukończę. Znam Django, więc nie widzę przeszkód, które mogły by mi to utrudnić.

**Comment by ad-m** [comment]
@mik-laj , potrzebujesz pomocy?
