### ISSUE TITLE
Zaktualizowanie instalacji i obsługi front-endu

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#338]
Plik https://github.com/watchdogpolska/small_eod/blob/dev/frontend-project/README.md jest nie aktualny uwzględniając uwagę z #333 na temat instalacji z yarnem. Poza tym jego formatowanie i zakres (demo) stwarza przestrzeń do usprawnień.

**Comment by magul** [comment]
Dla mnie zawartość tego pliku to:
 * README boilerplate'a stworzonego przez Ant Design Pro; opisuje podstawowe polecenie (jak `npm install` czy `npm start`); mamy to w dockerze uruchamiane za `Makefile`m, ja bym powiedział że nie ma co tego trzymać w README
 * informacje dodane przez @nnow991; tam jeszcze zamiast Markdown'a jest użyty czysty HTML; tam (zbyt) szczegółowo jest opisane, jak uruchomić projekt bez dockera, co u nas na chwilę obecną nie ma zastosowania); poza tym zawiera info o wersji demo (https://demo.small-eod.siecobywatelska.pl/admin/).

Osobiście informację o demo przeniósłbym do głównego README, a reszta wydaje mi się do zaorania :tractor:

**Comment by daxter44** [comment]
PR #568  chyba rozwiązuje to Issue ?

**Comment by ad-m** [comment]
Tak.
