### ISSUE TITLE
Lista spraw

### ISSUE THREAD

**Issue by SmietankowyImperator** [watchdogpolska/small_eod#386]
Stworzenie ekranu listy spraw
* tabela zawiera kolumny 
    * Nazwa (pole `name` w serializatorze)
    * Kontrolowana Instytucja (pole będzie pochodzić z osobnego żądania http w ramach #387)
    * Komentarz (pole `comment` w serializatorze) 
    * Utworzono (`createdOn`)
    * Zmodyfikowano (`modifiedOn`)
    * Tagi (`tags`)
    * Listy (`letterCount`)
* Ekran paginowy wielkość strony 20
* Ekran dostępny z menu bocznego

**Comment by mateuszmagulski** [comment]
chętnie się zajmę tym tematem

**Comment by ad-m** [comment]
@mateuszmagulski , czy zakres jest jasny? Potrzebujesz dodatkowego objaśnienia?

**Comment by mateuszmagulski** [comment]
@ad-m raczej wszystko jest jasne, jak gdzieś utknę, to będę dawał znać.

**Comment by mateuszmagulski** [comment]
Mam jeden problem: w serializerze `cases` i w api `cases` jest wartość `comment`, ale w odpowiedzi z SDK wartości tej nie ma. @ad-m czy to gdzieś utknęło w SDK?

**Comment by magul** [comment]
Myślę @mateuszmagulski że to kwestia nie podbicia wersji SDK. Tutaj masz pull request wystawiany automatycznie przez bota: https://github.com/watchdogpolska/small_eod/pull/357

Pytanie, czy przez te wszystkie zmiany z liczbą pojedynczą i mnogą nie będziemy mieć jakiś błędów. Jakbyś (w osobnym pull requeście najlepiej) podbił wersję SDK do najnowszej i sprawdził, że wszyskie (2 chyba) istniejące ekrany działają poprawnie to:
 * miałbyś zapewne `comment` jako obiekt w SKD
 * byłoby super.

**Comment by magul** [comment]
No i jak to potwierdzisz, to równie dobrze możemy zmergować #357, ja miałem (i mam póki co nadal) na liście sprawdzenie tej aktualizacji SDK ale śmiało, możesz zrobić to Ty, to mi spadnie z listy.

**Comment by mateuszmagulski** [comment]
ściągnąłem pull requesta #357, ale nadal nie udostępnia pola comment. Sprawdziłem również `collections` i jest to samo, nie widzi najnowszych zmian z liczbami pojedynczymi/mnogimi

**Comment by ad-m** [comment]
@mateuszmagulski , podstawowe pytanie...Czy dostajesz te informacje z API?
