### ISSUE TITLE
Kontrolowana instytucja na Liście spraw

### ISSUE THREAD

**Issue by SmietankowyImperator** [watchdogpolska/small_eod#387]
* Kolumna **Kontrolowana Instytucja** powinna zostać uzupełniona osobnym żądaniem HTTP, podczas oczekiwania na odpowiedź w miejscu na dane pojawia się spiner (https://ant.design/components/spin/)
* Zadanie jest uzależnione od #386

**Comment by ad-m** [comment]
Dodałbym, że w przypadku błędu pobierania w miejscu danych pojawia się identyfikator.

**Comment by SmietankowyImperator** [comment]
@ad-m Jakie proponujesz rozwiązanie ?

**Comment by magul** [comment]
Czy w takim wypadku pokazujemy na czerwono ten identyfikator i wyświetlamy informację o błędzie nad tabelą?

**Comment by magul** [comment]
(czy w ogóle to jest moment by zacząć rozmawiać o takim fallbacku?)

**Comment by ad-m** [comment]
Zgadzam się, że to nie moment, aby myśleć o takim fallbacku.
