### ISSUE TITLE
Usunięcie pola "name", zmiana pola "description" na "document_type"

### ISSUE THREAD

**Issue by mateuszmagulski** [watchdogpolska/small_eod#388]
AC1. Należy usunąć `name` z modelu Letter. Pole to nie jest używane.
AC2. Zmiana modelu `Description` na `DocumentType` (verbose name ustawiony na `Type of document`).
AC3. Zmiana pola `description` w modelu `Letter` na `document_type` wskazujące na `DocumentType` (verbose name ustawiony na `Type of document`).
AC4. Odpowiednia aktualizacja migracji, faktorek, serializerów i testów.
AC5. Aktualizacja SDK

Blokowane przez #389 - usunięcie pola `name` z tabeli w komponencie `TableList`.

Podzadanie dla #385

EDIT: uwzględniłem wyniki rozmowy z #409

**Comment by magul** [comment]
To, jak rozumiem dotyczy bazy danych, backendu, później SDK i listy na froncie?

**Comment by mik-laj** [comment]
Ja chce, ja chce!

**Comment by magul** [comment]
Tu myślę @mik-laj, że powinniśmy wziąć pod uwagę ustalenia z #409. Postaram się podmienić zaraz opis tego ticketa, żeby nie musieć już tego poprawiać.

**Comment by magul** [comment]
@mik-laj uwzgędniłem w opisie zadania wyniki rozmowy z #409. Dodatkowo dodałem do kryteriów akceptacji aktualizację SDK i wyrzucenie pola `name` z komponentu listów na froncie (dlatego dodałem label `front-end`).

Proponowałbym następującą kolejność prac (każdy punkt to osobny pull request):
 * usunięcie użycia `Letter.name` z frontu
 * zmiany na backendzie
 * aktualizacja SDK (tutaj być AFAIK GitHub Actions powinno to ogarnąć, ale pewnie możesz też sam wystawić pull request)
 * podbicie wersji SDK w `package.json` (tutaj @renovate-bot pewnie też wystawi pull request, jak tylko zauważy nowe commity na głównym branchu w `small-eod-client`).

**Comment by magul** [comment]
@mik-laj znalazłem #389 - pewnie to będzie blokować usunięcie pola z backnendu, więc ktoś musiałby to ogarnąć, zanim zaczniesz sprzątać w backendzie. (tzn. że ten pierwszy punk na liście pull requestów to dokładnie to, co jest w #389 )

**Comment by magul** [comment]
To jeszcze będzie wymagać przebudowania SDK https://github.com/watchdogpolska/small-eod-sdk-javascript/pull/6
