### ISSUE TITLE
Coś robimy źle z Reduxem

### ISSUE THREAD

**Issue by magul** [watchdogpolska/small_eod#391]
Zgłaszam na szybko, będzie trzeba więcej czasu na debugging, ale z jakiegoś powodu **side-efect** w modelu użytkownika przy uruchamianiu `fetchAll` dodaje do użytkowników tagi.

**Comment by kuskoman** [comment]
@magul chyba mam winowajcę https://github.com/watchdogpolska/small_eod/blob/dev/frontend-project/src/services/users.ts

**Comment by magul** [comment]
wygląda prawilnie. to zostawimy, może ktoś to ogarnie wchodząc w projekt.

**Comment by magul** [comment]
BTW pewnie to też spoko motyw, by zacząć pisać testy jednostkowe?

**Comment by kuskoman** [comment]
Ten akurat błąd by dało się wyłapać silnym typowaniem ale jestem za celowanie w 100% coverage storów (na testowanie komponentu można moim zdaniem dość mocno przymknąć oko)
