### ISSUE TITLE
wprowadzić zarządzanie listami w django-admin

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#395]
W ramach realizacji #393 potrzebujemy wprowadzić zarządzanie listami z pomocą django-admin.

Ekran z V1: https://demo.small-eod.siecobywatelska.pl/admin/cases/letter/
Kod z V1: https://github.com/watchdogpolska/small_eod/blob/master/small_eod/cases/admin.py

Uwaga: Zaszły zmiany wokół załączników.

**Comment by efefre** [comment]
@ad-m mogę zająć się tym zadaniem

**Comment by ad-m** [comment]
Chętnie przyjmiemy propozycje zmiany.

**Comment by efefre** [comment]
@ad-m czy w tej wersji też jest potrzebna akcja "download_selected_letters"? 
W poprzedniej wersji załączniki działały inaczej i nie bardzo wiem, jak teraz mogę zrobić taką funkcjonalność.

**Comment by ad-m** [comment]
Zapytanie do @mrbojko , gdyż przekazuje swoje obowiązki.

**Comment by efefre** [comment]
Zrobiłam PR bez akcji "download_selected_letters". Jak coś, to wydzielę to jako oddzielne zadanie.

**Comment by ad-m** [comment]
Świetnie, że wydzielasz na osobne zadanie, zamiast blokować problem.
