### ISSUE TITLE
zarzadzanie kanałami w django-admin

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#396]
W ramach realizacji #393 potrzebujemy wprowadzić zarządzanie kanałami z pomocą django-admin.

Ekran z V1: https://demo.small-eod.siecobywatelska.pl/admin/cases/channel/
Kod z V1: https://github.com/watchdogpolska/small_eod/blob/master/small_eod/cases/admin.py

**Comment by efefre** [comment]
W V1 było tylko:
`admin.site.register(Channel)`

W obecnej wersji widzę, że jest to odtworzone, więc moim zadaniem, zadanie do zamknięcia.
