### ISSUE TITLE
zarządzanie tagami w django-admin

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#398]
W ramach realizacji #393 potrzebujemy wprowadzić zarządzanie tagami z pomocą django-admin.

Ekran z V1: https://demo.small-eod.siecobywatelska.pl/admin/cases/tag/
Kod z V1: https://github.com/watchdogpolska/small_eod/blob/master/small_eod/cases/admin.py

**Comment by mik-laj** [comment]
Ekran v2: https://demo.small-eod.siecobywatelska.pl/admin/cases/tag/
Pracuje nad integracją Grappeli, ale teraz to tak wygląda.
<img width="382" alt="Screenshot 2020-06-24 at 02 59 40" src="https://user-images.githubusercontent.com/12058428/85484293-d5013680-b5c6-11ea-8ddc-2668776cd686.png">

**Comment by mik-laj** [comment]
Czy coś tutaj należy jeszcze zrobić?

**Comment by ad-m** [comment]
Jest wystarczające.

**Comment by mik-laj** [comment]
Czy powinnismy to zamknać?
