### ISSUE TITLE
zarządzanie listami za pośrednictwem sprawy w django-admin

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#399]
W ramach realizacji #393 potrzebujemy wprowadzić zarządzanie listami z pośrednictwem sprawy za pomocą django-admin. Polega to na tym, że podczas edycji sprawy uzyskuje się wykaz listów, które można edytować. Jest to kluczowe dla efektywnego wprowadzania dużej ilości listów, a także zarządzania ich kolejnością.

Problematyczna w tym zakresie będzie zarządzanie załącznikami, ze względu na ograniczenia django i zmiany sygnalizowane w #395 . 

Ekran z V1: https://demo.small-eod.siecobywatelska.pl/admin/cases/case/39/change/
Kod z V1: https://github.com/watchdogpolska/small_eod/blob/master/small_eod/cases/admin.py

**Comment by mik-laj** [comment]
Pracuje nad tym, aby dać możliwość wybór tagów za pomocąą autocomplete na tym ekranie

**Comment by ad-m** [comment]
Wprowadź django-grappeli tak jak w V1

**Comment by ad-m** [comment]
Wprowadzone.
