### ISSUE TITLE
zmiana automatycznego widoku sortowania listów

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/small_eod#4]
teraz listy w tabeli automatycznie sortują się wg daty wysłania/odebrania od najstarszej. Prośba o zmianę, żeby automatyczny był widok od najnowszej

**Comment by ad-m** [comment]
Zmieniono.

**Comment by AgnieszkaZdanowicz** [comment]
dzięki, teraz jest nam dużo łatwiej!
