### ISSUE TITLE
Lista Instytucji

### ISSUE THREAD

**Issue by SmietankowyImperator** [watchdogpolska/small_eod#405]
Stworzenie ekranu listy instytucji

* tabela zawiera kolumny:
    * Nazwa (pole `name` w serializatorze)
    * Komentarz
    * Utworzono (`createdOn`)
    * Zmodyfikowano (`modifiedOn`)
    * Tagi

Ekran paginowy wielkość strony 20
Ekran dostępny z menu bocznego

**Comment by ad-m** [comment]
Uwagi do mnie skorygowane w #436 (pola dodane)

**Comment by daxter44** [comment]
Można zamknąć #550

**Comment by ad-m** [comment]
Dziękuje
