### ISSUE TITLE
Tabela "Opisy listów"

### ISSUE THREAD

**Issue by magul** [watchdogpolska/small_eod#409]
W starej wersji aplikacji (__v1__) mamy tabelę "Opisy listów" (w kodzie nazwaną `LetterName`, która zawiera tylko jedno pole ("opis", w kodzie `content`). Ta tabela łączy się tabelą "Listy" (w kodzie `Letter`) za pomocą relacji jeden-do-wielu (`ForeignKey`).

W nowej wersji (__v2__) mamy w aplikacji `letter` model `Description` (który obecnie nie jest dostępny z poziomu Django Admina i nie da się go dodać z poziomu edycji "Listu") - mamy też na modelu `Letter` pole `name`, które jest w Django Adminie opisane jako `Descirption`.

W #385 zapropnowane zostało usunięcie pola `name` z modelu `Letter` i używanie połączenia `Letter` do modelu `Description`.

Stąd moje pytania:
 * czym jest `description` czysto biznesowo? czy to znaczy, że to jest skończony zbiór opisów (i te same opisy mogą występować w różnych listach)? czy to nie powino być pole na swobodny opis?
 * czy powinniśmy przygotować listę `Description` w Ant Design Pro, tak jak ona jest dostępna w Django Admin?

cc @ad-m @AgnieszkaZdanowicz

**Comment by AgnieszkaZdanowicz** [comment]
Zamiast "opis" może być "rodzaj dokumentu"

Pozdrawiam
Agnieszka Zdanowicz


ul. Ursynowska 22/2 | 02-605 Warszawa
KRS: 0000181348
tel: +48 22 844 73 55 <+48228447355>
www.siecobywatelska.pl | www.sprawdzamyjakjest.pl
www.watchdogportal.pl | www.informacjapubliczna.org



śr., 10 cze 2020 o 23:55 Adam Dobrawy <notifications@github.com> napisał(a):

**Comment by magul** [comment]
Myślę, że pewnie kilka tematów jeszcze wyjdzie podczas migracji (nad którą pracuję już mentalnie @ad-m , więc bądź gotowy na pytania).

W każdym raize zakłądając, że zmieniamy z  _opis_ (`description`) albo _nazwa_ (`name`) na _rodzaj dokumentu_ (`document_type`) to cały czas zasadne zostaje pytanie, czy tego nie powinniśmy po prostu traktować jak _cechę_ w rozumieniu #410? Widziałem w przykładzie, który @ad-m przysłałeś, że jest dużo wartości, które można tam wybrać, może to jest powód, dla którego powinno to być inne pole, niż _cecha_?

**Comment by magul** [comment]
Dobra, jeszcze w sumie jedno pytanie odnośnie #388  - czy w wypadku, gdy nazywamy to pole jako `document_type`, to dowolne pole tekstowe `name` powinniśmy usuwać? Czy takie pole nie ma dla Was wartości @AgnieszkaZdanowicz ?

**Comment by AgnieszkaZdanowicz** [comment]
Nie do końca wiem, które to pole "name". Czy dobrze Was rozumiem, że kiedyś obecne pole "Description" to było pole "name", ale zmieniło się z opisowego na ole wyboru i dlatego też zmieniło nazwę?
Jako swobodne pole opisu w liście mamy "komentarz", więc nie potrzebujemy drugiego takiego pola. Moim zdaniem można usunąć pole "name".

**Comment by magul** [comment]
Dobra, to ja się lekko zakręciłem @AgnieszkaZdanowicz  - znalazłem zmianę z marca 2019, w której @ad-m zmienia te pole ze swobodnym opisem na pole wyboru (https://github.com/watchdogpolska/small_eod/commit/fc212865ad01904d23ea21ce494112609a7b2e7b).

Mi się wydaje, że wszystkie tematy poruszyliśmy, ten ticket zamykam i będziemy to realizować w #389 i #388.
