### ISSUE TITLE
Błędny typ lista spraw

### ISSUE THREAD

**Issue by mateuszmagulski** [watchdogpolska/small_eod#433]
https://github.com/watchdogpolska/small_eod/blob/fe6feb3b947f308ac3fbff90870529a804c4ea29/frontend-project/src/pages/cases/list/index.tsx#L19-L25

Tutaj powinien być typ `number[]` zamiast `[number]`. 
Typ number[] informuje o tablicy zawierającej elementy typu number, natomiast typ [number] o tablicy zawierającej dokładnie jeden element typu number. 

@kuskoman, czy dobrze myślę?

**Comment by kuskoman** [comment]
@mateuszmagulski dobrze myślisz, musiało mi umsknąć jak przeglądałem PR
powinno być `number[]`, ewentualnie `Array<number>`

teraz zauważyłem, że ten błąd występuje również w interfejsie Case z pliku frontend-project/src/services/cases.ts z [tego](https://github.com/watchdogpolska/small_eod/commit/fe6feb3b947f308ac3fbff90870529a804c4ea29#diff-a5245ef5cbe02965b33863fd76a7660b) commita

**Comment by kuskoman** [comment]
Myślę, że warto podlinkować #341 jak argument dla użycia ban types dla niektórych typów

**Comment by kuskoman** [comment]
@mateuszmagulski z ciekawości- miałeś z tego powodu błędy, czy kod przechodził bez problemów (nie chce mi się sprawdzać samemu)?
bo mimo wszystko kod jest poddany typecheckowi przez kompilacją, a kod, oprócz interfejsów był prawidłowy, i wynikowy javascript powinien powstać taki sam

**Comment by mateuszmagulski** [comment]
Błędów nie było. Jak coś jeszcze wzbudzi moje wątpliwości będę pisał.
