### ISSUE TITLE
Przeniesienie fetchowania Institutions do store'a Reduxowego

### ISSUE THREAD

**Issue by kuskoman** [watchdogpolska/small_eod#439]
Jak zauważył @magul w #403 fetchowanie instytucji w https://github.com/watchdogpolska/small_eod/commit/fe6feb3b947f308ac3fbff90870529a804c4ea29#diff-fcd909aa4f097b1b98b7e1b710d9fc99 w `frontend-project/src/components/Table/InstitutionName.tsx` lepiej pasowałoby do stora reduxowego, więc po przemyśleniu, w myśl zasady DRY i dla utrzymania spójności w projekcie proponuję tam go przenieść.

**Comment by magul** [comment]
Ja tylko dodam, że temat dotyczy też kanałów i spraw.
