### ISSUE TITLE
wymiana interfejsu użytkownika

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#46]
Obecny interfejs oparty jest o Django-Admin. To pozwoliło wykonać szybko prototyp, który sprawdził się. Jednak takie podejście nie pozwala na wprowadzenie większej logiki i rodzi szereg ograniczeń.

Musimy to zmienić. Możemy pójść dwoma drogami:
- monolitycznie, gdzie serwer renderuje kod HTML - podobnie jak wykonane zostało fedrowanie, poradnia,
- nowocześnie, z pełniejszą izolacją warstwy prezentacji - z wykorzystaniem Vue (mam w nim skromne doświadczenie), AngularJS (mniejsze), albo innego narzędzia, które nowa osoba weźmie w opiekę.

Nowoczesne podejście wymaga przygotowania API, o którym mowa w #31.

**Comment by magul** [comment]
To wygląda jak "epik nad epikami". Myślę, że już się zdecydowaliśmy na Ant Design Pro i Redux'a pod spodem, zamykam, a poszczególne wymagania dostarczymy w osobnych ticketach.

**Comment by ad-m** [comment]
W pełni się zgadzam. To było ponad rok temu, gdy poczuliśmy potrzebę zejścia z django-admina :)
