### ISSUE TITLE
Podwójny interface dla Institution

### ISSUE THREAD

**Issue by mateuszmagulski** [watchdogpolska/small_eod#466]
Aktualnie mamy dwa interfejsy dla Institution, jeden w: `services/institutions.ts` i drugi w `models/institutions.ts`. 
Chcę to ujednolicić, gdzie chcemy trzymać takie interfejsy? Stworzyć nowy katalog do tego?

**Comment by magul** [comment]
@kuskoman co myślisz?

**Comment by kuskoman** [comment]
@magul umknął mi jakoś ten mention w powiadiomieniach w tonie security warningów
w tym momencie mamy dwa **różne** interfejsy dla (zakładam) tych samych obiektów
myślę, że w przypadku gdy nie modyfikujemy struktury obiektu dostarczanego nam przez bazę danych nie ma potrzeby redundancji obiektu, który ma służyć do tego samego- w razie, gdyby okazało się, że potrzebujemy zmodyfikować obiekt najprawdopodobniej albo posłuży do tego osobna funkcja z własnym return typem albo po prostu utworzymy jeszcze raz interfejs w modelu- nie powinno być z tym problemu

**Comment by mateuszmagulski** [comment]
W takim razie gdzie chcemy przechowywać interfejsy obiektów? W modelach, serwisach, czy osobnych plikach w np. katalogu interfaces? Uważam, że dobrze byłoby trzymać się jednego schematu.

**Comment by kuskoman** [comment]
@mateuszmagulski oczywiście. myślę, że najsensowniej będzie trzymać w serwisie- jeśli zmienialibyśmy sdk od razu podmieni wszystkie użyte interfejsy
