### ISSUE TITLE
Dodanie komantarza i tagów do serializera Institutions

### ISSUE THREAD

**Issue by mateuszmagulski** [watchdogpolska/small_eod#481]
Lista instytucji wymaga komentarzy i tagów (name z modelu Tags).

**Comment by pifry** [comment]
Chętnie zajmę się tematem. Proszę o przypisanie.

**Comment by magul** [comment]
Hey @pifry - trzy sprawy:
 * dodałem Ciebie do współpracowników przy tym projekcie (będziesz musiał jeszcze przyjąć to zaproszenie), dzięki temu będziesz w stanie sam się przypisywać do zadań (między innymi)
 * mamy (nowego) Slacka: [https://join.slack.com/t//t/codeforpoznan/shared_invite/zt-8a7u52j8-yqB01C2YgYF4Lvd1pFM_jw](https://join.slack.com/t//t/codeforpoznan/shared_invite/zt-8a7u52j8-yqB01C2YgYF4Lvd1pFM_jw); szukaj tam kanału #watchdog
 * zespół pracujący nad aplikacją zdzwania sie na pół godziny co 2 tygodnie w środę; następne spotkanie mamy zaplanowane za tydzień, jakby co zapraszamy (szczegółowe dane są przypięte jako wiadomość w kanale na Slacku).

**Comment by pifry** [comment]
Link do slacka nie działa. Możesz sprawdzić, czy jest poprawny.

**Comment by magul** [comment]
Ok, faktycznie wkradła się literówka. Link do Slacka: https://join.slack.com/t/codeforpoznan/shared_invite/zt-8a7u52j8-yqB01C2YgYF4Lvd1pFM_jw
