### ISSUE TITLE
documentType w modelu Letters

### ISSUE THREAD

**Issue by mateuszmagulski** [watchdogpolska/small_eod#482]
Aktualnie API dla listów udostępnia pk typu dokumentu. Jeśli zmienimy pk na name, (tak jak w przypadku tags, w spawach), pozbędziemy się dodatkowego żądania.

**Comment by ad-m** [comment]
Nie jestem przekonany do takiej zmiany. Żądania do API możemy także zniwelować odpowiednim cache tych danych w przeglądarce. Jednocześnie przypuszczam, że zakres znaków w opisie listów może być szerszy niż w tagach.

@AgnieszkaZdanowicz , pociąga to za sobą, że rodzaj dokumentu (obecny opis listu) nie będzie mógł ulegać zmianie. Czy ulega zmianie?

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m chodzi Ci o to, czy po uzupełnieniu raz pola "opis listu" potem zdarza nam się zmieniać wartość w tym polu? Tak i to dosyć często

**Comment by ad-m** [comment]
@ad-m, nie o wartość polu listu, a np. zmiana "wycofanie zawiadomienia" na "wycofanie zawiadomienia o przestępstwie" np. tu https://small-eod.siecobywatelska.pl/admin/cases/lettername/357/change/ .

**Comment by AgnieszkaZdanowicz** [comment]
To rzadziej w takim razie. Ostatnio robiłam porządek, bo staram się, żeby było maksymalnie 100 opisów. Widzę, że teraz jest 107, więc znowu powinnam uporządkować. Ale to raczej znaczy, że część opisów kasuję, a listy do których dany opis był dodany dodaję do innego opisu. Więc teraz już raczej nie zmieniamy treści opisów.

**Comment by ad-m** [comment]
Raczej nie zmieniamy, ale to nie jest coś tak ulotnego jak tagi i chcemy zachować możliwość edycji bez edytowania wszystkiego.

@mateuszmagulski, mając na względzie powyższe, czy potrzebujesz potrzebę zmian w API?

**Comment by mateuszmagulski** [comment]
@ad-m nie jest to niezbędne, to była raczej propozycja. Dzięki za wyjaśnienie.
