### ISSUE TITLE
instytucje - filtrowanie + sortowanie

### ISSUE THREAD

**Issue by SmietankowyImperator** [watchdogpolska/small_eod#485]
Stworzenie wyszukiwarki w widoku Instytucji

Wyszukiwanie po kolumnach:
* Nazwa (pole `name` w serializatorze)
* Komentarz (`comment`)

Sortowanie po kolumnach:
* Nazwa (`name`)
* Komentarz (`comment`)
* Utworzono (`created`)
* Zmodyfikowano (`modified`)

Dopuszcza się sortowanie tylko po jednej kolumnie w opcjach:
* malejąco
* rosnąco

**Comment by ad-m** [comment]
Czy takie zagadnienia powinniśmy osobno rozpisywać (choćby w postaci dwóch powiązanych zagadnień) dla front-endu, a osobno dla back-endu?
