### ISSUE TITLE
Potrzebujemy {Event,Letter}CollectionViewSetTestCase

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#495]
Podobne do obecnego NoteCollectionViewSetTestCase. Nie potrzebujemy na początku żadnych specyficznych testów, same generyczne. 

@JakubWolak, kolejne zagadnienie, które może Ci podpasować.

**Comment by ad-m** [comment]
@efefre , czy miałabyś ochotę zając się tym zagadnieniem? Ta klasa https://github.com/watchdogpolska/small_eod/blob/dev/backend-project/small_eod/collections/tests/test_views.py#L86 wymaga rozszerzenia na sąsiednie przypadki. Przydałoby się także w tym obszarze poprawić nazwy klas na zaproponowane w nagłówku https://github.com/watchdogpolska/small_eod/blob/dev/backend-project/small_eod/collections/views.py#L98  , bo obecnie - przez moje przeoczenie - powtarzają się w projekcie https://github.com/watchdogpolska/small_eod/search?q=NoteViewSet .

**Comment by efefre** [comment]
Ok. Postaram się zająć tym tematem.

**Comment by efefre** [comment]
Rozbiję to zadanie na dwa PR, bo muszę jeszcze zrozumieć o co chodzi z `queries_less_than_limit` (nie wiem jak ustalać tę wartość). Do zrobienia zostało mi `LetterCollectionViewSetTestCase', a obecnie tam właście zwraca mi błąd z tą wartością.

**Comment by ad-m** [comment]
`queries_less_than_limit` zabezpiecza nad przed niekontrolowaną eksplozją liczby zapytań. W Django łatwo przypadkiem sprawić, że liczba drastycznie wzrośnie, więc wprowadzamy limit, aby świadomie musiał on być podniesiony wraz z wzrostem widoku. Zobacz na PR, gdy to weszło tj. #163 i #487.

**Comment by ad-m** [comment]
Cieszy mnie, że sama organizujesz i dzielisz zadania na mniejsze :+1:

**Comment by efefre** [comment]
Zrealizowane w całości.
