### ISSUE TITLE
Wprowadzić sortowanie w API

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#496]
Jak dostrzeżono w #486 i #485 mechanizm sortowania odpowiedzi jest wymagany. Nie musi to być coś skomplikowanego.

Django-REST-Framework daje inspiracje na temat https://www.django-rest-framework.org/api-guide/filtering/#orderingfilter 
Demo small_eod v1 dają inspiracje na temat funkcjonalności.

- [ ] Rozważyć skonsultowanie z front-endem jak wykonać interfejs przyjemny w konstrukcji.
- [ ] Zachować sortowanie jak w small_eod v1 (@AgnieszkaZdanowicz , przydaje Ci się sortowanie po wielu polach?)
- [ ] Odnotować zmiany w dokumentacji OpenAPI
- [ ] Zmianę wprowadzić dla wszystkich zasobów
- [ ] Umożliwić sortowanie po kolumnach jak w V1, jeżeli występują w V2 odpowiedniki.
- [ ] Wprowadzić podstawe testy (najlepiej generyczne) dla sortowania.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m tak, sortowanie po wielu polach jest przydatne

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz , dla jasności, masz na myśli jednoczesne (pierw według jednej kolumny, potem według kolejnej tam, gdzie są identyczne wartości) sortowanie (nie filtrowanie) po wielu polach?

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m tak :)

**Comment by ad-m** [comment]
OK, czyli będziemy musieli to uwzględnić i przetestować taki przypadek także.

**Comment by ad-m** [comment]
@fivelamps, może to? Przypuszczam, że najwięcej czasu zajmie udokumentowanie w OpenAPI (Swagger) nowych parametrów w generyczny sposób.

**Comment by fivelamps** [comment]
Ok. Gdzie mogę zobaczyć demo v1?

**Comment by ad-m** [comment]
@fivelamps , na https://demo.small-eod.siecobywatelska.pl/admin/ jest demo. Na branchu master jest możliwość uruchomienia. Do hostowanego demo napisz na Slacku lub na adam.dobrawy@siecobywatelska.pl w sprawie hasła.

**Comment by ad-m** [comment]
@fivelamps , jak idzie? Podczas ostatniego środowego spotkania (co 2 tygodnie o godzinie 20) ustalono, że to staje się dość istone, gdyż front-end chciałby dodać po swojej stronie filtrowanie.

**Comment by fivelamps** [comment]
@ad-m , idzie dobrze, chyba że o czymś nie wiem. Jutro postaram się wrzucić PR z sortowaniem dla Letters. Jeśli zaakceptujesz, to powinnam szybko móc to rozciągnąć na resztę zasobów.

**Comment by ad-m** [comment]
Działano w  #505 . @fivelamps , czy chcesz tu coś dodać?
