### ISSUE TITLE
Dodanie akcji download_selected_letters w django-admin

### ISSUE THREAD

**Issue by efefre** [watchdogpolska/small_eod#539]
W ramach realizacji #395 zostało odtworzone zarządzanie listami w django-admin zgodne z V1.
Ze względu na inny sposób działania załączników w obecnej wersji, została pominięta akcja "**download_selected_letters**".

Kod z V1: https://github.com/watchdogpolska/small_eod/blob/master/small_eod/cases/admin.py

@mrbojko, czy ta akcja jest potrzebna w nowej wersji?

**Comment by mrbojko** [comment]
@efefre tak, uważamy, że jest to ważna i przydatna funkcjonalność z punktu widzenia użytkowników systemu.

**Comment by ad-m** [comment]
@efefre , gdzie widzisz trudność w implementacji? Możesz wpaść na statut to omówić? Najbliższe 23 wrzesnia o godzinie 20:00 pod linkiem https://meet.google.com/pfa-yxgi-kho .  W https://github.com/watchdogpolska/small_eod/blob/master/small_eod/cases/admin.py#L87 zapisujesz plik z użyciem ścieżki, ale możesz użyć iteratora https://pypi.org/project/zipstream-new/ a następnie pobierania pliku z użyciem requests w strumieniu (zob. https://requests.readthedocs.io/en/master/user/quickstart/#raw-response-content ).

**Comment by efefre** [comment]
Ok. Postaram się zająć tym zadaniem. Teraz wydaje mi się to mniej skomplikowane niż wcześniej myślałam.

**Comment by efefre** [comment]
@ad-m  Mam problem z formatowaniem kodu. Przed wysłaniem PR zrobiłam lokalnie make fmt i niby mój plik admin jest ok, a tu w testach zgłasza błąd. 
Za to lokalnie pokazuje mi inne pliki do poprawki - te które Ty ostatnio poprawiałeś grupowo. Na testach nie ma do nich uwag.

Czy to możliwe, że mam jakąś inną wersję black? Jak mogę to sprawdzić?

**Comment by ad-m** [comment]
Pobierz najnowszy obraz kontenera black, bo używasz starego z cache. Daj znać, jeżeli nie wiesz o co chodzi to Ci napisze dokładne polecenie.

Pozdrawiam z telefonu

**Comment by efefre** [comment]
Poszło, dzięki. Wcześniej żle kombinowałam z tą aktualizacją. Myślałam, że mam ostatnią wersję, ale faktycznie, właśnie się zaktualizowała.

**Comment by efefre** [comment]
> @efefre , gdzie widzisz trudność w implementacji? Możesz wpaść na statut to omówić? Najbliższe 23 wrzesnia o godzinie 20:00 pod linkiem https://meet.google.com/pfa-yxgi-kho .  W https://github.com/watchdogpolska/small_eod/blob/master/small_eod/cases/admin.py#L87 zapisujesz plik z użyciem ścieżki, ale możesz użyć iteratora https://pypi.org/project/zipstream-new/ a następnie pobierania pliku z użyciem requests w strumieniu (zob. https://requests.readthedocs.io/en/master/user/quickstart/#raw-response-content ).

Nie wyrobiłam się na dzisiejszy statut. Macie jakieś cykliczne spotkania? Mam wrażenie, że Slack "umarł". Jest jakieś inne miejsce do kontaktu?

**Comment by ad-m** [comment]
Używamy obecnie Slacka https://join.slack.com/t/codeforpoznan/shared_invite/enQtNjQ5MTU1MDI0NDA0LWNhYTA3NGQ0MmQ5ODgxODE3ODJlZjc3NWE0NTMzZjhmNDBkN2QwMzNhYWY5OWQ5MGE2OGM3NjAyODBlY2VjNjU kanał #watchdog . 
W projekcie w 6 tygodniach nie było tak wiele zmian, więc na Slacku nie wiele się działo. Większość kwestii była omawiana na statusach, które dzieją się co dwa tygodnie w środy o godzinie 20 pod znanym linkiem.

**Comment by efefre** [comment]
Dzięki. Nie znałam tego nowego placka. Sprawdzałam ciągle starego :)

**Comment by ad-m** [comment]
Już posprzątałem starego i także pod twoim impulsem trochę spisałem sposób funkcjonowania.
