### ISSUE TITLE
Spotkania statusowe projektu small-eod

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#547]
W projekcie regularnie odbywają się spotkania statutowe. Czas je udokumentować i sformalizować.

Podczas spotkań statusowych przedstawiane jest:

- przedstawienie projektu dla osób nowych,
- podsumowanie zmian, napotkanych trudności i innych barier,
- dyskusja "biznesu" z programistami, aby sprawnie wyjaśnić ewentualne wątpliwości, ustalić priorytety i kierunki biznesowe,
- dyskusja programistów co do kierunków technicznych projektu,
- dyskusja na temat zagadnień wymagających rozmowy oznaczonych etykietą "[to discuss](https://github.com/watchdogpolska/small_eod/issues?q=label%3A%22to+discuss%22)"
- przydzielenie zadań do następnego spotkania.
 
Spotkania odbywają się w co drugą środę o godzinie 20:00 z wykorzystaniem Google Meet pod odnośnikiem:
https://meet.google.com/pfa-yxgi-kho .

Najbliższe spotkania:

- [ ] 7 października 2020 godz. 20:00
- [ ] 21 października 2020 godz. 20:00
- [ ] 4 listopada 2020 godz. 20:00
- [ ] 18 listopada 2020 godz. 20:00

Subskrybuj ten wątek, aby dowiedzieć się o wszelkich odstępstwach.

**Comment by ad-m** [comment]
Wolałbym podlinkować kalendarz, ale zagadnienie https://github.com/CodeForPoznan/Community/issues/80 jes otwarte.

**Comment by ad-m** [comment]
Przypominam, że to dziś!

**Comment by kuskoman** [comment]
To tym razem ja przypomnę

**Comment by magul** [comment]
Ja tylko napiszę, że udostępniliśmy publicznie kalendarz (w końcu!) googlowski i można się subskrybować tutaj: https://calendar.google.com/calendar/u/0/embed?src=hello@codeforpoznan.pl&ctz=Europe/Warsaw
