### ISSUE TITLE
zbiorcze pobieranie listów przypisanych do danej sprawy

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/small_eod#55]
Bardzo by nam się przydała już teraz możliwość pobierania za pomocą jednego kliknięcia wszystkich listów przypisanych do sprawy.  Np. mamy sprawę z UM Bytomia, gdzie są 42 listy. Ja chcę udostępnić dziennikarzowi wszystkie te dokumenty, to muszę je pobrać. Jakby się to robiło jednym kliknięciem, to byłoby super. Pomyślałam, że to możliwe do zrobienia, jak udało się na poradni :) Czy to będzie trudne?

**Comment by ad-m** [comment]
Postaram się dziś podczas podróży pociągiem wykonać i wdrożyć.

**Comment by ad-m** [comment]
Niestety, łącze mi na to nie pozwala. Będę chciał to szybko dodać,  bo 42 kliknięcia na jednej sprawie za kilka minut odtwórczej pracy.

**Comment by AgnieszkaZdanowicz** [comment]
Adamie, czy dziś dasz radę usiąść do tej zmiany?

**Comment by ad-m** [comment]
Wykonane.
