### ISSUE TITLE
Naprawienie type errors

### ISSUE THREAD

**Issue by kuskoman** [watchdogpolska/small_eod#555]
Obecnie użycie polecenia `yarn tsc` skutkuje wyrzuceniem errorów do konsoli.

**Comment by daxter44** [comment]
<img width="1440" alt="Zrzut ekranu 2020-10-1 o 22 33 53" src="https://user-images.githubusercontent.com/9075439/94860399-4eb28700-0436-11eb-88a7-7d8cd0afd7f4.png">
Chodzi o te errory ?

**Comment by kuskoman** [comment]
@daxter44 tak. umi kompiluje TS korzystając z jakiegoś swojego configa i nie łapie tych błędów

**Comment by daxter44** [comment]
Z ostatnim szybko sobie poradziłem, z tym typem globalnym to bym prosił o wytłumaczenie czy jest już jakiś typ na którym mógłbym się wzorować ? jeżeli nie, to gdzie taki typ w strukturze projektu powinienem umieścić bo raczej nie w /src/models/ :)

**Comment by kuskoman** [comment]
@daxter44 plik typings.d.ts (dodanie do niego nowych typów jest dobrym rozwiązaniem)
ten link może (nie musi) być przydatny:
https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-modifying-module-d-ts.html
