### ISSUE TITLE
Sortowanie dokumentów według sprawy

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#557]
Szanowna @AgnieszkaZdanowicz ,

> * formularz sprawy umożliwia:
>    * bezpośrednie dodanie powiązanych z daną sprawą listów (w Django to było wykonane przez inline), ze względu na dokonywanie archiwizacji "teczek" sprawy, czyli przetwarzania zbioru dokumentów należących do jednej sprawy, z uwzględnieniem:

Czy wykorzystujesz sortowania listów manualnego? Może lepiej sortować zawsze po dacie przesyłki?

![image](https://user-images.githubusercontent.com/3618479/94350434-9d36de80-004e-11eb-8e15-23fafaa6770b.png)

Mniej ręcznej pracy, mniej zabawy, a możemy zrobić, że jak to pole jest nie wypełnione to sortuje się po dacie dodania.

**Comment by AgnieszkaZdanowicz** [comment]
@ad-m nie stosuję ręcznego. Super by było, gdyby się układało samo, ale nie po dacie dodania, a po dacie odbioru/nadania. Bo jak uzupełniamy stare teczki, to wtedy nie dodajemy listów w takiej kolejności, jak przyszły, tylko różnie.

**Comment by ad-m** [comment]
Super, to upraszcza element, który postrzegałem za kosztowny.

**Comment by ad-m** [comment]
@daxter44, masz ochotę na to zagadnienie? Należy usunąć pole `ordering` z modelu `Letter` ( https://github.com/watchdogpolska/small_eod/blob/dev/backend-project/small_eod/letters/models.py#L44 ). Myślę, że sposób sortowania to już zagadnienie dla front-endu.
@mrbojko , dokumentacja projektu może zostać zaktualizowana o uproszczone wymagania.

**Comment by daxter44** [comment]
No spoko :)

**Comment by daxter44** [comment]
@ad-m do zamknięcia ?
