### ISSUE TITLE
Uproszczenie setupu dla potrzeb front-endu

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#581]
@kuskoman wskazał na problem w zakresie budowy naszego front-endu na Windows. Myślę, że możemy to uprościć, zważywszy na to, że nasz back-end jest w dobrej kondycji. 

Proponuje:

- wyeliminować Nginxa - pliki statyczne serwować przez Django (dewelopersko), a następnie tunelować przez front-end proxy ( https://github.com/watchdogpolska/small_eod/blob/dev/frontend-project/config/config.ts#L234-L240 )
- zrealizować #219 w celu możliwości wykorzystania publicznej instancji back-endu
- udostępnienie publicznej instancji back-endu na potrzeby rozwoju samego front-endu

W celu udostępnienia publicznej instancji back-endu sprzyjać będzie to, że planujemy mieć w tym zakresie CI & CD, więc back-end będzie świeży.

**Comment by ad-m** [comment]
Uprzejmie proszę o głosy sprzeciwu i krytyki.

Zakładam, że taki flow będzie alternatywny dla obecnego flow Dockerowego wymagającego w praktyce Linuxa.

**Comment by kuskoman** [comment]
Generalnie problemem nie był sam system (przynajmniej dla mnie- WSL2 radzi sobie z Dockerem świetnie) ale skoro proponowane rozwiązanie eliminuje niedogodności, z którymi miałem do czynienia to jestem jak najbardziej za :)
Dodam, że prawdopodobnie dodatkowo obniży to wymagany próg wejścia dla projektu
