### ISSUE TITLE
Dokumentacja jako strona internetowa

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#586]
Obecnie mamy dokumentacje w `/docs`, która dokumentuje wąski obszar projektu tj. wymagania. Część rzeczy tam wymaga aktualizacji np. dokumentacja API, bo została zrealizowana. Uważam, że dokumentacja front-endu powinna być razem z dokumentacją back-endu. Może nawet dokumentacje aplikacji zintegrowanych (GMail - #3, WebDAV - #99, skaner - #152) także.

Ja bym proponował użyć do tego sphinx & readthedocs, ale może front-end będzie miał lepsze propozycje. @kuskoman , uprzejmie proszę o opinie.

**Comment by kuskoman** [comment]
@ad-m generalnie najczęściej używałem vuepressa ale Twoja propozycja brzmi jak najbardziej ok

**Comment by ad-m** [comment]
Sphinx dzięki readthedocs.org oferuje CI&CD&hosting out of the box. Nie trzeba tego niemal konfigurować. Jako że jest to Python to będzie łatwo wygenerować dokumentację klas itd.

**Comment by ad-m** [comment]
Zatem do wykonania:

- [ ] początkowy setup Sphinx
- [ ] migracja istniejącej dokumentacji (przy okazji prawdopodobnie ocena dokumentacji przestarzałej lub powtórzonej)

**Comment by ad-m** [comment]
@efefre , czy pracowałaś z Sphinx ( https://www.sphinx-doc.org/en/master/ )? To taki standard dla dokumentacji w świecie Python, więc jak idziesz w kierunku Python to może Cię to zagadnienie zainteresować.

**Comment by efefre** [comment]
Nie miałam wcześniej do czynienia z Sphinx. Rozeznam temat.

**Comment by ad-m** [comment]
Spójrz na Fedrowanie, bo tam mamy w ten sposób wykonaną dokumentacje.

Inspiracją może być także Apache Airflow: https://github.com/apache/airflow/

Zacznijmy jednak od czegoś małego i ujednolicenia tego co mamy, aby zacząć utrzymywać dokumentacje wraz z wprowadzanymi zmianami.

**Comment by ad-m** [comment]
W zakresie samego pisania dokumentacji w szerszym aspekcie warto zapoznać się z:
https://github.com/thegooddocsproject/templates
https://documentation.divio.com/

**Comment by ad-m** [comment]
https://docs.airbyte.io/architecture/tech-stack prezentuje ciekawy podział treści.
