### ISSUE TITLE
dodanie jeszcze jednego pola w sekcji sprawy -  “instytucja skarżona”

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/small_eod#6]
Mam prośbę o dodanie jeszcze jednego pola w sekcji sprawy -  “instytucja skarżona”. Bo w tej chwili nie mamy, jak wyszukać np. wszystkich spraw, które mieliśmy z Ministerstwem Cyfryzacji

**Comment by ad-m** [comment]
Zrobione.

**Comment by AgnieszkaZdanowicz** [comment]
ok
