### ISSUE TITLE
 odczyt wykazu jednostek administracyjnych w postaci tabeli 

### ISSUE THREAD

**Issue by mrbojko** [watchdogpolska/small_eod#604]
Potrzebujemy stworzenie ekranu listy jednostek administracyjnych na podstawie

Dokumentacja API: http://localhost:8000/api/redoc/#operation/administrative_units_list
Dokumentacja SDK: https://github.com/watchdogpolska/small-eod-sdk-javascript/blob/master/docs/AdministrativeUnitsApi.md

Tabela zawiera kolumny:

- nazwa (pole `name` w API)

Ekran paginowy wielkość strony 20.
Ekran dostępny z menu górnego.

**Comment by kuskoman** [comment]
Nie robiłem chyba  jeszcze żadnych features, mogę wziąć

**Comment by ad-m** [comment]
@SmietankowyImperator , dlaczego dodałeś etykietę back-end, skoro samo zgłoszenie wskazuje, że jest to obsługiwane przez API i SDK ergo back-end jest zaimplementowany?

**Comment by SmietankowyImperator** [comment]
@ad-m bezwiednie wrzuciłem za poleceniem @mrbojko ;)
Ponoc takie labels przypisałeś w markdownowym dokumencie. Rzeczywiscie mozna usunąć niepotrzebny tag
