### ISSUE TITLE
Niekompletny wykaz endpointów API w /api

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#624]
Na `/api` (np. https://dev.small-eod.siecobywatelska.pl/api/ ) nie mamy kompletnego wykazu endpointów API. Kompletny jest dostępny przez ReDoc np. na https://dev.small-eod.siecobywatelska.pl/api/redoc/ .

Powinniśmy to naprawić, bo wprowadza ryzyko mylnego wrażenia co do zakresu API.

**Comment by kkarpieszuk** [comment]
wybaczcie nowicjuszowi w django, ale czy to jest aż tak proste, czy jednak to dirty hack? :)

**Comment by NameeLesS** [comment]
Mogę się tym zająć
