### ISSUE TITLE
dodanie Tagu

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#630]
Opis (co jest wymagane, wymagane implementacyjne, kryteria akceptacji):
* Potrzebujemy stworzenie ekranu z formularzem do dodania cechy.
* Formularz zawiera wszystkie pola dostępne w operacji api `tags_create`.
* Ekran dostępny z menu górnego i z wykazu cech.

Powiązane zagadnienia:
* zarządzanie tagami - #629
* dodanie Cechy - #616 (przykład)

Pomocne materiały:
* Dokumentacja API: https://dev.small-eod.siecobywatelska.pl/api/redoc/#tag/Tags
* Dokumentacja SDK: https://github.com/watchdogpolska/small-eod-sdk-javascript/blob/master/docs/TagsApi.md

**Comment by daxter44** [comment]
Biorę to, ale czekam na #616 żeby robić według standardu :)

**Comment by ad-m** [comment]
To może weźmiesz #616 i wyznaczysz standard? :)

**Comment by daxter44** [comment]
@ad-m Pracowałem, pracowałem jednak przerósł mnie błąd zwracany z API 
"detail": "CSRF Failed: CSRF token missing or incorrect."
Mimo iż do żądania dołączony był tag CSRF. 
<img width="838" alt="Zrzut ekranu 2020-10-12 o 22 59 06" src="https://user-images.githubusercontent.com/9075439/95789997-dcb42a80-0cde-11eb-9b55-5b88df187a16.png">
nie pomogła nawet zmiana na 
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
w base.py

**Comment by ad-m** [comment]
Co masz w body odpowiedzi? CSRF nie powinien mieć nic do rzeczy w przypadku API:

```
$ curl https://{user}:{pass}@dev.small-eod.siecobywatelska.pl/api/tags/ -v -XPOST -H "Content-Type: application/json" -d '{"name":"X"}'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 62.181.9.114...
* Connected to dev.small-eod.siecobywatelska.pl (62.181.9.114) port 443 (#0)
* found 127 certificates in /etc/ssl/certs/ca-certificates.crt
* found 520 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: dev.small-eod.siecobywatelska.pl (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=dev.small-eod.siecobywatelska.pl
* 	 start date: Sun, 02 Aug 2020 23:38:07 GMT
* 	 expire date: Sat, 31 Oct 2020 23:38:07 GMT
* 	 issuer: C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
* Server auth using Basic with user 'root'
> POST /api/tags/ HTTP/1.1
> Host: dev.small-eod.siecobywatelska.pl
> Authorization: Basic {cut}
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 12
> 
* upload completely sent off: 12 out of 12 bytes
< HTTP/1.1 201 Created
< Server: nginx/1.19.1
< Date: Mon, 12 Oct 2020 21:16:01 GMT
< Content-Type: application/json
< Content-Length: 20
< Allow: GET, POST, HEAD, OPTIONS
< Referrer-Policy: same-origin
< Status: 201 Created
< Vary: Accept
< X-Content-Type-Options: nosniff
< X-Powered-By: Phusion Passenger 6.0.6
< Strict-Transport-Security: max-age=16000000; preload
< X-Frame-Options: SAMEORIGIN
< 
* Connection #0 to host dev.small-eod.siecobywatelska.pl left intact
{"id":51,"name":"X"}
```

**Comment by ad-m** [comment]
Spushuj to co masz i zrób draft PR. Zobaczymy.

**Comment by daxter44** [comment]
Mam pytanie odnośnie komunikacji z API przez SDK. Mianowicie, 
`   tagsCreate(data) {
      return this.tagsCreateWithHttpInfo(data)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }`
SDK zwraca tylko dane, bez HTTP status code, jak w takim razie użytkownikowi pokazać czy operacja się udała 200- 201 czy np. Tag jest już zajęty http 400 czy nie ma uprawnień http 403 ? Dodatkowo, przydało by się Issue do implementacji elementów pokazujących użytkownikowi czy operacja się udała bądź nie, alerty wbudowane są w ant design https://ant.design/components/alert/

**Comment by ad-m** [comment]
> Mam pytanie odnośnie komunikacji z API przez SDK

@daxter44 , skoro potrzebujesz bardziej szczegółowych informacji to dlaczego nie użyjesz `tagsCreateWithHttpInfo`, które sam wskazujesz?

> przydało by się Issue do implementacji elementów pokazujących użytkownikowi czy operacja się udała bądź nie, alerty wbudowane są w Ant Design.

Każdy może tworzyć nowe zagadnienia. Zapraszam ;-) Ja traktowałem jako element "standardu", ale dostrzegam, że warto do tego elementu podejść oddzielnie.

**Comment by daxter44** [comment]
@ad-m Przeczytałem komentarz i sam się w głowę uderzyłem, ze tych metod nie skojarzyłem. Ślepo zapatrzyłem się w przyklad użycia Api :)

**Comment by ad-m** [comment]
Odnośnie dzielenia zadań na mniejsze to w  #495 jest dobry przykład od @efefre samoorganizacji. Najważniejsze, aby być świadom co jest jeszcze do zrobienia, aby niedokończone funkcje nie zakłóciły produkcji i pracy innym.

**Comment by daxter44** [comment]
@ad-m Drobną próbę ogarnięcia alertów podjąłem w PR #658
