### ISSUE TITLE
edycja instancji Tagu

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#631]
Każda sprawa może mieć przypisane. Znaczniki pozwalają elastycznie zgrupować sprawy, które mają wspólny charakter np. stanowią realizacje jednego monitoringu, bowiem często wysyłamy to samo zapytanie do wielu instytucji. Wówczas każde zapytanie do kolejnej instytucji to osobna sprawa, ale wszystkie te sprawy łączy wspólny tag.

Opis (co jest wymagane, wymagane implementacyjne, kryteria akceptacji):

* Potrzebujemy stworzenie ekranu z formularzem do dodania nowego Tagu.
* Formularz zawiera wszystkie pola dostępne w operacji api `tags_partial_update`.
* Ekran dostępny z wykazu Tagów.
* Rozwiązanie spójne z standardem formularzy edycji (zob. #606).
* Back-end został zaimplementowany – jeżeli nie wiesz jak go użyć, napisz tu komentarz.

Powiązane zagadnienia:

* zarządzanie tagami - #629
* edycja cechy - #617 (przykład)

Pomocne materiały:
* Dokumentacja API: https://dev.small-eod.siecobywatelska.pl/api/redoc/#tag/Tags
* Dokumentacja SDK: https://github.com/watchdogpolska/small-eod-sdk-javascript/blob/master/docs/TagsApi.md

**Comment by MichalKarol** [comment]
Zamknięte przez #716.
