### ISSUE TITLE
odczytanie wykazu Użytkowników

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#634]
Wykorzystujemy do zapewnienia rozliczalności tzw. konta użytkownika. Każdy użytkownik ma przypisane uprawnienia do pracy w systemie (Django standard). Pełen zbiór użytkowników (ze względu na back-officowy charakter systemu) nie stanowi sekretu.

Opis (co jest wymagane, wymagane implementacyjne, kryteria akceptacji):
* Potrzebujemy wprowadzić wykaz, który umożliwi odczytanie Użytkowników w systemie. Wystarczająca jest prosta tabela.
* dodanie opcji do menu górnego
* Rozwiązanie spójne z dotychczas wykorzystywanymi
* Back-end został zaimplementowany – jeżeli nie wiesz jak go użyć, napisz tu komentarz.
* Kontrola uprawnień wejdzie później, a decyduje i tak back-end.

Powiązane zagadnienia:

* zarządzanie użytkownikami - #633
* wykaz JST - #604 (przykład)

Pomocne materiały:
* Dokumentacja API: https://dev.small-eod.siecobywatelska.pl/api/redoc/#tag/users
* Dokumentacja SDK: https://github.com/watchdogpolska/small-eod-sdk-javascript/blob/master/docs/UsersApi.md

**Comment by MichalKarol** [comment]
Zamknięte przez #720.
