### ISSUE TITLE
edycja instancji Użytkownika

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#636]
Wykorzystujemy do zapewnienia rozliczalności tzw. konta użytkownika. Każdy użytkownik ma przypisane uprawnienia do pracy w systemie (Django standard). Pełen zbiór użytkowników (ze względu na back-officowy charakter systemu) nie stanowi sekretu.

Opis (co jest wymagane, wymagane implementacyjne, kryteria akceptacji):

* Potrzebujemy stworzenie ekranu z formularzem do dodania nowego Użytkownika.
* Formularz zawiera wszystkie pola dostępne w operacji api `users_partial_update`.
* Ekran dostępny z wykazu Użytkowników.
* Rozwiązanie spójne z standardem formularzy edycji (zob. #606).
* Back-end został zaimplementowany – jeżeli nie wiesz jak go użyć, napisz tu komentarz.
* Kontrola uprawnień wejdzie później, a decyduje i tak back-end.

Powiązane zagadnienia:

* zarządzanie użytkownikami - #633
* edycja cechy - #617 (przykład)

Pomocne materiały:
* Dokumentacja API: https://dev.small-eod.siecobywatelska.pl/api/redoc/#tag/users
* Dokumentacja SDK: https://github.com/watchdogpolska/small-eod-sdk-javascript/blob/master/docs/UsersApi.md

**Comment by MichalKarol** [comment]
Zamknięte przez #720.
