### ISSUE TITLE
usuniecie instancji Użytkownika

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#637]
Wykorzystujemy do zapewnienia rozliczalności tzw. konta użytkownika. Każdy użytkownik ma przypisane uprawnienia do pracy w systemie (Django standard). Pełen zbiór użytkowników (ze względu na back-officowy charakter systemu) nie stanowi sekretu.

Opis (co jest wymagane, wymagane implementacyjne, kryteria akceptacji):

* Potrzebujemy stworzenie ekranu do usuwania Użytkowników.
* Formularz zawiera wszystkie pola dostępne w operacji api `users_delete`.
* Operacja dostępna z widoku szczegółowego Użytkownika i z wykazu Użytkowników.
* Rozwiązanie spójne w zakresie usuwania z innymi elementami (zob. #606)
    * Do zastanowienia się czy wykorzystamy nowy ekran, okno modalne, czy podajnik (drawer). Proponuje dla akcji takich jak usunięcie wykorzystać podajnik (drawer) na początek.
* Back-end został zaimplementowany – jeżeli nie wiesz jak go użyć, napisz tu komentarz.

Powiązane zagadnienia:

* zarządzanie użytkownikami - #633
* usunięcie cechy - #618 (przykład)

Pomocne materiały:
* Dokumentacja API: https://dev.small-eod.siecobywatelska.pl/api/redoc/#tag/users
* Dokumentacja SDK: https://github.com/watchdogpolska/small-eod-sdk-javascript/blob/master/docs/UsersApi.md

**Comment by MichalKarol** [comment]
Zamknięte przez #720.
