### ISSUE TITLE
zarządzanie kanałami komunikacji

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#638]
Każdy list może mieć przypisany *Kanał komunikacji* (ang. `Channel`). Określa on w jakiej postaci dokument został dostarczony do Stowarzyszenia. W przyszłości będzie mógł być także wykorzystywany do określenia jak dokument ma zostać wysłany przez Stowarzyszenie, a także jakie metadane adresowe musimy mieć określone dla instytucji, aby faktycznie wykorzystywać dany kanał komunikacji.

W ramach zarządzania potrzebujemy elementów standardowego słownika:

* wykaz (wykonane)
* dodawanie
* edycja (odczyt)
* usuwanie

**Comment by daxter44** [comment]
Po ogarnięciu tagu wziąłem się za to issue, i mam je już prawie gotowe. Działa :
wykaz (wykonane)
dodawanie
usuwanie
Problem mam z :
