### ISSUE TITLE
odczytanie wykazu Wydarzeń

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#643]
Zapoznaj się pierw z #642, aby zrozumieć kontekst zagadnienia.

Opis (co jest wymagane, wymagane implementacyjne, kryteria akceptacji):
* Potrzebujemy wprowadzić wykaz, który umożliwi odczytanie Wydarzeń w systemie. Wystarczająca jest prosta tabela.
* dodanie opcji do menu górnego
* Rozwiązanie spójne z dotychczas wykorzystywanymi
* Back-end został zaimplementowany – jeżeli nie wiesz jak go użyć, napisz tu komentarz.
* Kontrola uprawnień wejdzie później, a decyduje i tak back-end.

Powiązane zagadnienia:

* zarządzanie wydarzeniami - #642
* wykaz JST - #604 (przykład)

Pomocne materiały:
* Dokumentacja API: https://dev.small-eod.siecobywatelska.pl/api/redoc/#tag/events
* Dokumentacja SDK: https://github.com/watchdogpolska/small-eod-sdk-javascript/blob/master/docs/EventsApi.md

**Comment by MichalKarol** [comment]
Closed by #723
