### ISSUE TITLE
dodanie Wydarzenia

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#644]
Zapoznaj się pierw z #642, aby zrozumieć kontekst zagadnienia.

Opis (co jest wymagane, wymagane implementacyjne, kryteria akceptacji):
* Potrzebujemy stworzenie ekranu z formularzem do dodania Wydarzeń.
* Formularz zawiera wszystkie pola dostępne w operacji api `events_create`.
* Ekran dostępny z menu górnego i z wykazu Wydarzeń.
* Kontrola uprawnień wejdzie później, a decyduje i tak back-end.

Powiązane zagadnienia:
* zarządzanie wydarzeniami - #642
* dodanie Tagu - #630 (przykład)

Pomocne materiały:
* Dokumentacja API: https://dev.small-eod.siecobywatelska.pl/api/redoc/#tag/events
* Dokumentacja SDK: https://github.com/watchdogpolska/small-eod-sdk-javascript/blob/master/docs/EventsApi.md

**Comment by MichalKarol** [comment]
Closed by #723
