### ISSUE TITLE
edycja instancji Wydarzenia

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#645]
Zapoznaj się pierw z #642, aby zrozumieć kontekst zagadnienia.

Opis (co jest wymagane, wymagane implementacyjne, kryteria akceptacji):

* Potrzebujemy stworzenie ekranu z formularzem do dodania nowego Wydarzenia.
* Formularz zawiera wszystkie pola dostępne w operacji api `events_partial_update`.
* Ekran dostępny z wykazu Wydarzeń.
* Rozwiązanie spójne z standardem formularzy edycji (zob. #606).
* Back-end został zaimplementowany – jeżeli nie wiesz jak go użyć, napisz tu komentarz.
* Kontrola uprawnień wejdzie później, a decyduje i tak back-end.

Powiązane zagadnienia:

* zarządzanie wydarzeniami - #642
* edycja cechy - #617 (przykład)

Pomocne materiały:
* Dokumentacja API: https://dev.small-eod.siecobywatelska.pl/api/redoc/#tag/events
* Dokumentacja SDK: https://github.com/watchdogpolska/small-eod-sdk-javascript/blob/master/docs/EventsApi.md

**Comment by MichalKarol** [comment]
Closed by #723
