### ISSUE TITLE
dodanie Sprawy

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#652]
Zapoznaj się pierw z #623, aby zrozumieć kontekst zagadnienia.

Opis (co jest wymagane, wymagane implementacyjne, kryteria akceptacji):
* Potrzebujemy stworzenie ekranu z formularzem do dodania Sprawy.
* Formularz zawiera wszystkie pola dostępne w operacji api `cases_create`.
* Ekran dostępny z menu górnego i z wykazu Spraw.
* Kontrola uprawnień wejdzie później, a decyduje i tak back-end.

Powiązane zagadnienia:
* zarządzanie sprawami - #623
* dodanie Tagu - #630 (przykład)

Pomocne materiały:
* Dokumentacja API: https://dev.small-eod.siecobywatelska.pl/api/redoc/#tag/cases
* Dokumentacja SDK: https://github.com/watchdogpolska/small-eod-sdk-javascript/blob/master/docs/CasesApi.md

**Comment by rwakulszowa** [comment]
Postaram się tym zająć w ramach wdrożenia do projektu.

**Comment by ad-m** [comment]
Wczoraj został dodany na to PR.

**Comment by ad-m** [comment]
#712

**Comment by rwakulszowa** [comment]
O, ok.
W takim razie poszukam analogicznej sprawy.

**Comment by MichalKarol** [comment]
@rwakulszowa: Jeszcze #712 nie przeszło review, ale są duże dobre review. Rzuć okiem i zobacz czy warto by było odbranchować się od mojego PRa jak będziesz robić coś z CRUDam, bo dość uprościłem pare rzeczy. @ad-m: Jak myślisz?

**Comment by rwakulszowa** [comment]
@MichalKarol jasne, na pewno będę używał nowości z 712 w kodzie. Póki co i tak będę zapoznawał się z projektem, więc nie ma pośpiechu.

**Comment by MichalKarol** [comment]
Closed by #712
