### ISSUE TITLE
edycja instancji Sprawy

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#653]
Zapoznaj się pierw z #623, aby zrozumieć kontekst zagadnienia.

Opis (co jest wymagane, wymagane implementacyjne, kryteria akceptacji):
* Potrzebujemy stworzenie ekranu z formularzem do dodania Sprawy.
* Formularz zawiera wszystkie pola dostępne w operacji api `cases_create`.
* Ekran dostępny z wykazu Spraw.
* Kontrola uprawnień wejdzie później, a decyduje i tak back-end.

Powiązane zagadnienia:
* zarządzanie sprawami - #623
* dodanie Tagu - #630 (przykład)

Pomocne materiały:
* Dokumentacja API: https://dev.small-eod.siecobywatelska.pl/api/redoc/#tag/cases
* Dokumentacja SDK: https://github.com/watchdogpolska/small-eod-sdk-javascript/blob/master/docs/CasesApi.md

**Comment by MichalKarol** [comment]
Closed by #712
