### ISSUE TITLE
usuniecie instancji Sprawy

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#654]
Zapoznaj się pierw z #623, aby zrozumieć kontekst zagadnienia.

Opis (co jest wymagane, wymagane implementacyjne, kryteria akceptacji):

* Potrzebujemy stworzenie ekranu do usuwania Spraw.
* Formularz zawiera wszystkie pola dostępne w operacji api `cases_delete`.
* Operacja dostępna z widoku szczegółowego Spraw i z wykazu Spraw
* Rozwiązanie spójne w zakresie usuwania z innymi elementami (zob. #606)
    * Do zastanowienia się czy wykorzystamy nowy ekran, okno modalne, czy podajnik (drawer). Proponuje dla akcji takich jak usunięcie wykorzystać podajnik (drawer) na początek.
* Back-end został zaimplementowany – jeżeli nie wiesz jak go użyć, napisz tu komentarz.

Powiązane zagadnienia:

* zarządzanie sprawami - #623
* usunięcie cechy - #618 (przykład)

Pomocne materiały:
* Dokumentacja API: https://dev.small-eod.siecobywatelska.pl/api/redoc/#tag/cases
* Dokumentacja SDK: https://github.com/watchdogpolska/small-eod-sdk-javascript/blob/master/docs/CasesApi.md

**Comment by MichalKarol** [comment]
Closed by #712
