### ISSUE TITLE
usuniecie instancji Listu

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#657]
Zapoznaj się pierw z #655, aby zrozumieć kontekst zagadnienia.

Opis (co jest wymagane, wymagane implementacyjne, kryteria akceptacji):

* Potrzebujemy stworzenie ekranu do usuwania Listu.
* Formularz zawiera wszystkie pola dostępne w operacji api `letters_delete`.
* Operacja dostępna z widoku szczegółowego Listów i z wykazu Listów
* Rozwiązanie spójne w zakresie usuwania z innymi elementami (zob. #606)
    * Do zastanowienia się czy wykorzystamy nowy ekran, okno modalne, czy podajnik (drawer). Proponuje dla akcji takich jak usunięcie wykorzystać podajnik (drawer) na początek.
* Back-end został zaimplementowany – jeżeli nie wiesz jak go użyć, napisz tu komentarz.

Powiązane zagadnienia:

* zarządzanie listami - #655
* usunięcie cechy - #618 (przykład)

Pomocne materiały:
* Dokumentacja API: https://dev.small-eod.siecobywatelska.pl/api/redoc/#tag/letters
* Dokumentacja SDK: https://github.com/watchdogpolska/small-eod-sdk-javascript/blob/master/docs/LettersApi.md

**Comment by michalczukm** [comment]
Bierzemy temat z @gtktsc

**Comment by michalczukm** [comment]
PR: https://github.com/watchdogpolska/small_eod/pull/749

**Comment by michalczukm** [comment]
Done. Można zaktualizować status ticket'a :)
