### ISSUE TITLE
Dodanie banneru powered-by-vercel.svg

### ISSUE THREAD

**Issue by mrbojko** [watchdogpolska/small_eod#671]
Do stopki każdej strony należy dodać banner powered-by-vercel.svg

**Comment by ad-m** [comment]
Czy możesz przedstawić kontekst?

Czy możesz przedstawić plik?

Czy logo ma być dostępne we wszystkich, czy tylko we wdrożonych z pośrednictwem Vercel?

**Comment by mrbojko** [comment]
Adam Dobrawy zdecydował włączeniu Vercel do projektu https://github.com/watchdogpolska/small_eod/pull/613 
Aby skorzystać z programu sponsorskiego musimy umieścić logo Vercel na wszystkich stronach projektu, zgodnie z instrukcją:
https://vercel.com/knowledge/can-vercel-sponsor-my-project
Plik powered-by-vercel.svg pojawi się w pilkach projektu gdy PR https://github.com/watchdogpolska/small_eod/pull/670 zostanie zaaprobowany.

**Comment by daxter44** [comment]
<img width="1436" alt="Zrzut ekranu 2020-10-19 o 21 41 56" src="https://user-images.githubusercontent.com/9075439/96503701-f5c75900-1253-11eb-805a-ebe295a04c89.png">
To logo musi być takie duże ? :)

**Comment by ad-m** [comment]
Ja bym pliku nie zmieniał (taki przesłali), a ewentualnie dowscaling wprowadził po stronie styli. Wystaw PR to prześlemy do Vercel o akceptacje.

**Comment by ad-m** [comment]
Dobrze byłoby logo umieścić także na stronie ekranu logowania (stopki można ujednolicić), zwłaszcza z uwagi na obecny stan formularza logowania (mogą nie przebrnąć do logo).

**Comment by mrbojko** [comment]
@daxter44 wydaje mi się, że rozmiar i tak wymusiła wysokość linii tekstu? Obłóż klasą CSS wtedy łatwiej będzie rgulować rozmiar (nawet ja dam radę zrobić stosownego PRa ;-) Mniejsza wersja wygląda OK

**Comment by daxter44** [comment]
@ad-m ujednoliciłem stopki poprzez utworzenie komponentu DefaultFooter, który wstawiłem zarówno w BasicLayout jak i UserLayout (strona logowania). 
@mrbojko Opakowalem logo klasą .logo_vercel znajdującym się w frontend-project/src/components/GlobalFooter/DefaultFooter.less :)
