### ISSUE TITLE
Back-port wydarzeń z v2 do v1

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#685]
Obecnie informacje o rozprawach rejestrujemy poza small-eod w tzw. "panelu Stowarzyszenia". Panel jest przestarzałą aplikacją wytworzoną bez wsparcia jego wytwórcy (członka Stowarzyszenia). Dojrzały twór w PHP. WZCC podjęło ponad rok temu uchwałę o jego likwidacji.

@AgnieszkaZdanowicz aby ułatwić pracę zaczęła tworzyć kalendarze na Google Kalendarz, aby umożliwić rejestrowanie informacji o sprawach sądowych. Dostrzegam, że to nam dokłada pracy przy migracji do V2, ale w pełni rozumiem potrzebę w obliczu migracji 

Z tego względu potrzebujemy zbackportować do V1 zarządzanie wydarzeniami (#642), które w zakresie back-endu zostało wykonane. Dodatkowo potrzebujemy także ich eksportowania (#684). Back-port nie powinien skomplikować procesu migracji, bo model będzie zsynchronizowany.

**Comment by AgnieszkaZdanowicz** [comment]
A to nie wiedziałam, że to utrudni potem migrację, sorry!

**Comment by ad-m** [comment]
Jedno miejsce więcej skąd należy pobrać dane, więc to w oczywisty sposób dodatkowy koszt. 

Dodatkowo w Kalendarzu dane nie mają poprawnego oznaczenia do sprawy, więc trzeba by mapować to symbolach sprawy sądowej lub ręcznie przypisać, co jest podatne na błędy.
