### ISSUE TITLE
Add Vercel URL to Vercel Banner

### ISSUE THREAD

**Issue by mrbojko** [watchdogpolska/small_eod#687]
Aby spełnić wymagania Vercela musimy do banneru w stopce dodać link: 
http://vercel.com/?utm_source=watchdogpolska&utm_campaign=small_eod
@daxter44 dałbyś radę dorzucić?

**Comment by ad-m** [comment]
@mrbojko , na ten temat jest już PR (#678), a także pierwotne zagadnienie (#671), które wciąż jest otwarte. W przyszłości proponuje takie elementy przedstawiać w komentarzu do PR, jeżeli istnieje.

**Comment by daxter44** [comment]
@mrbojko  @ad-m  poprawiłem url w ramach PR #678
