### ISSUE TITLE
zmiana nazwy dotychczasowego pola “instytucja” na “od kogo/do kogo” w sekcji listy

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/small_eod#7]
Prośba o zmianę nazwy dotychczasowego pola “instytucja” na “od kogo/do kogo” w sekcji listy. Dotychczasowa nazwa była myląca - nie było wiadomo, czy chodzi o instytucję skarżoną czy o instytucje, od której dostaliśmy list/ do której wysłaliśmy list

**Comment by ad-m** [comment]
Nie podoba mi się taka nazwa, bo nie jest spójna z resztą, ale dodałem pole pomocy, które łatwo mogę dodać.
