### ISSUE TITLE
nie działający formularz logowania we front endzie

### ISSUE THREAD

**Issue by kkarpieszuk** [watchdogpolska/small_eod#709]
witam po raz pierwszy, trafilem na ogloszenie ze szukacie pomocy i pomyslalem ze ze sprobuje

we front endzie nie dam rady sie zalogowac. 
steps to replicate: 
- uruchom serwer z dockera i utworz konto admina, dodaj testowe dane
- odwiedz http://localhost:8000
- zostaniesz przekierowany na http://localhost:8000/user/login z formularzem logowania
- wpisz login i haslo
- kliknij przycisk Submit
- efekt: nic sie nie dzieje. 

jest to zapewne spowodowane bledami js (zobacz zrzut ekranu)
![Zrzut ekranu z 2020-11-19 21-33-56](https://user-images.githubusercontent.com/2388617/99721334-5514c500-2aaf-11eb-8b51-7bc029db84d3.png)

tresci bledow na czerwono:
Zablokowano żądanie do zasobu innego pochodzenia: zasady „Same Origin Policy” nie pozwalają wczytywać zdalnych zasobów z „http://localhost:3000/umiui/info?t=1605811324702” (nieudane żądanie CORS).
ui socket init 
Object { type: "close", bubbles: false, cancelable: false, timeStamp: 1605811324795, wasClean: false, code: 1002, reason: "Cannot connect to server" }
index.js:1
[React Intl] Missing message: "menu.login" for locale: "pl-PL", using default message as fallback. index.js:1

Najbardziej obstawiam ten drugi, bo probowalem tez branch `master` i tam był tylko ten błąd i też nie można się zalogować. 

formularz na https://dev.small-eod.siecobywatelska.pl/user/login  mi działa (akurat ktos chyba skasowal konto root, ale przycisk działa, w konsoli nie ma błędów)

instalacje wykonałem wg wskazowek z readme, czyli `git clone...`, `docker-composer up`, potem `docker-compose run backend python manage.py createsuperuser` i `docker-compose run backend python manage.py init_data`

http://localhost:8000/admin działa ok, widze standardowy panel administracyjny django

**Comment by ad-m** [comment]
1/ W zakresie logowania do frontendu to  #167 stanowi, że element nie funkcjonuje. Jest to otwarte na PR.

Można przejść na https://dev.small-eod.siecobywatelska.pl/cases/list wprowadzić w powiadomieniu `root` i `root`, a wówczas istnieje możliwość wyświetlenie listy listów.

W zakresie problemów w konsoli to nie są one powiązane. Dobrze byłoby posprzątać, aby umijs wiedziało, że mamy z przodu nginx.

2/ Branch `master` zawiera zupełnie inne wydanie aplikacji. Wydanie na branchu `dev` powstało od zera. Od strony implementacji to są dwa projekty.

**Comment by kkarpieszuk** [comment]
ok, rozumiem, zamykam. dziekuje za wyjasnienia

**Comment by ad-m** [comment]
Cieszę się, że pytasz, zamiast tkwić w problemie :+1:
