### ISSUE TITLE
Problem z deployem na #dev

### ISSUE THREAD

**Issue by MichalKarol** [watchdogpolska/small_eod#721]
Run ./.github/actions/h1-cli

/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/a5e12cdb-b50e-4616-a017-eabbdfccd00c -f /home/runner/work/_temp/b5376109-8d1f-4861-9836-1b88d605a74b

Successfully installed h1-cli

Error: Unable to process command '::add-path::/home/runner/work/_temp/a5e12cdb-b50e-4616-a017-eabbdfccd00c' successfully.

Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by ad-m** [comment]
Fixed by #722
