### ISSUE TITLE
dodanie opcji przeszukiwania z lupki w sprawach

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/small_eod#8]
Teraz w widoku sprawy jest opcja tylko filtrowania:

![image](https://user-images.githubusercontent.com/36925935/48945796-f3efa080-ef2b-11e8-964c-04894afdecd1.png)

natomiast w listach jest też lupka. Czy w sprawach też może być taka lupka?

**Comment by ad-m** [comment]
Zrobionee.

**Comment by ad-m** [comment]
Aktualizacje wgrane na serwer.

**Comment by AgnieszkaZdanowicz** [comment]
dzięki, wszystko wygląda super!
