### ISSUE TITLE
nie działa pole wyboru przy dodawaniu listu

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/small_eod#84]
Jak dodajemy list, to jest takie pole, gdzie zaczynamy wpisywać tekst i pole podpowiada pasujące wyniki:

![image](https://user-images.githubusercontent.com/36925935/69556491-1552f480-0fa5-11ea-9665-975d3d47a557.png)

W tej chwili pole podpowiada, ale nie można wybrać żadnego z wyników. Trzeba wchodzić w lupkę i tam wyszukiwać, wybierać i tak się da.

**Comment by ad-m** [comment]
W tym zakresie nastąpiła zmiana, gdyż wcześniej było inaczej?

**Comment by ad-m** [comment]
Możesz wybrać CTRL + R w przeglądarce?

**Comment by AgnieszkaZdanowicz** [comment]
Jak odświeżyłam, to działa, przepraszam

**Comment by ad-m** [comment]
Pewnie #78 wprowadziło zmianę, która musiała być wczytana do pamięci przeglądarki, a po #83 wgrałem aktualizacje na serwer.
