### ISSUE TITLE
brakuje paska do przesuwania widoku 

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/small_eod#87]
Jak się wchodzi w spis listów: https://small-eod.siecobywatelska.pl/admin/cases/letter/, to nie widać całej tabelki, a brakuje suwaka na dole do przesunięcia widoku. Żeby widzieć całą tabelkę, muszę oddalić widok do 50%, a wtedy trudno to odczytać. Wydaje mi się, że wcześniej ten suwak był.

![image](https://user-images.githubusercontent.com/36925935/69962068-88142080-150d-11ea-825a-f59d95b34cd8.png)

**Comment by ad-m** [comment]
W zakresie CSS nie wiem jak to rozwiązać. W nowym UI problem nie będzie występować.

**Comment by AgnieszkaZdanowicz** [comment]
To mam nadzieję, że nowe UI szybko wejdzie :) to jest o tyle dziwne, że ten pasek był i znikł w pewnym momencie

**Comment by mrbojko** [comment]
@AgnieszkaZdanowicz czy wciąż nie widzisz paska? Bo wiem, że to głupia odpowiedź, ale u mnie jest i to w różnych przeglądarkach:
![obraz](https://user-images.githubusercontent.com/47541542/94373943-1abf2500-0109-11eb-976a-d6c60155c7fe.png)

**Comment by AgnieszkaZdanowicz** [comment]
@mrbojko sorry, zapomniałam zamknąć - już wszystko dobrze działa
