### ISSUE TITLE
automatyczne wyświetlanie wartości na listach rozwijanych

### ISSUE THREAD

**Issue by AgnieszkaZdanowicz** [watchdogpolska/small_eod#9]
Mam prośbę, o ile to możliwe, o zmianę sposobu wyświetlanych (podpowiadanych) wyników przy uzupełnianiu pola "instytucja" w sprawach. Teraz wyświetlają się instytucje dodane w kolejności dodania i trudno wyszukać odpowiednią. Poza tym system wyszukuje nazwy tylko po pierwszych literach. Inne wyświetlanie jest w instytucjach w listach. Na przykładzie: szukam Wojewódzkiego Sądu Administracyjnego w Gliwicach. 
1. w sprawach muszę wpisać "wojewódzki..." a on i tak wyszukuje tylko pierwszy wojewódzki sąd (tu akurat w Łodzi) i tego w Gliwicach muszę szukać ręcznie i to nie wiadomo gdzie, bo nie pamiętam, kiedy go dodawałam
2. w listach mogę wpisać "Gliwicach" i chociaż to słowo ze środka nazwy, to i tak wyświetli mi wszystkie instytucje, które mają to słowo w nazwie.

Wolę tę drugą opcję i prosiłabym o zastosowanie tego drugiego rozwiązania do wyświetlania podpowiedzi przy uzupełnianiu pola "instytucja" w sekcji "sprawy".

**Comment by ad-m** [comment]
@AgnieszkaZdanowicz ten mechanizm to jest "autocomplete". Jest on możliwy. Przeoczenie, że nie dodałem od razu. Dodatkowo zmieniłem kolejność instytucji, aby w wykazie instytucji były według nazwy także. Zrobione.

**Comment by AgnieszkaZdanowicz** [comment]
Dzięki! teraz czeka na wgranie na serwer, prawda?

Agnieszka Zdanowicz

Dyrektorka Zarządzająca

<http://siecobywatelska.pl/>

Sieć Obywatelska Watchdog Polska
ul. Ursynowska 22/2 | 02-605 Warszawa
KRS: 0000181348
tel: +48 22 844 73 55 <+48228447355> | fax: +48 22 207 24 09
www.siecobywatelska.pl | www.watchdogportal.pl | www.informacjapubliczna.org


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

wt., 27 lis 2018 o 21:11 Adam Dobrawy <notifications@github.com> napisał(a):

**Comment by ad-m** [comment]
W przypadku Sprawy pole "Kontrolowana instytucja" została naprawione:
![obraz](https://user-images.githubusercontent.com/3618479/49117628-a2d00b80-f2a1-11e8-8d4f-916318c7aab0.png)

Pozostało jednak w ramach pole "Instytucja" przy liście :unamused: Zaraz się za nie wezmę.

**Comment by ad-m** [comment]
Zrobione.
