### ISSUE TITLE
Missing code parameter in response.

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#936]
Obecnie na środowisku deweloperskim front-end nie przekazuje parametru `code` podczas uwierzytelniania:

```
App 228 output: Traceback (most recent call last):
App 228 output:   File "/data/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
App 228 output:     response = get_response(request)
App 228 output:   File "/data/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
App 228 output:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
App 228 output:   File "/data/env/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
App 228 output:     return view_func(*args, **kwargs)
App 228 output:   File "/data/env/lib/python3.7/site-packages/rest_framework/viewsets.py", line 125, in view
App 228 output:     return self.dispatch(request, *args, **kwargs)
App 228 output:   File "/data/env/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
App 228 output:     response = self.handle_exception(exc)
App 228 output:   File "/data/env/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
App 228 output:     self.raise_uncaught_exception(exc)
App 228 output:   File "/data/env/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
App 228 output:     raise exc
App 228 output:   File "/data/env/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
App 228 output:     response = handler(request, *args, **kwargs)
App 228 output:   File "/data/small_eod/backend-project/small_eod/users/views.py", line 86, in exchange
App 228 output:     profile = self.provider.exchange(request)
App 228 output:   File "/data/small_eod/backend-project/small_eod/users/providers.py", line 30, in exchange
App 228 output:     authorization_response=request.build_absolute_uri(),
App 228 output:   File "/data/env/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 240, in fetch_token
App 228 output:     authorization_response, state=self._state
App 228 output:   File "/data/env/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/clients/web_application.py", line 203, in parse_request_uri_response
App 228 output:     response = parse_authorization_code_response(uri, state=state)
App 228 output:   File "/data/env/lib/python3.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 274, in parse_authorization_code_response
App 228 output:     raise MissingCodeError("Missing code parameter in response.")
App 228 output: oauthlib.oauth2.rfc6749.errors.MissingCodeError: (missing_code) Missing code parameter in response.
172.28.0.3 - - [10/May/2021:02:28:04 +0000] "GET /api/users/exchange/ HTTP/1.1" 500 145 "https://dev.small-eod.siecobywatelska.pl/login/callback?state=...&code=...&scope=email%20profile%20openid%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email&authuser=2&hd=siecobywatelska.pl&prompt=none" "OpenAPI-Generator/1.0.4/Javascript" "62.181.9.114"
```

Stan się utrzymuje, pomimo przegenerowania front-endu ( https://github.com/watchdogpolska/small_eod/runs/2541824235?check_suite_focus=true ) po przegenerowaniu SDK.

CD działa poprawnie dla front-endu.

@MichalKarol czego nie wziąłem pod uwagę?

**Comment by MichalKarol** [comment]
Musisz poczekać na update sdk. Jak sdk się przebuduje, wtedy trzeba przebudować front jeszcze raz. :/ Sry, powinno iść w dwóch PR jednak.  @ad-m

**Comment by MichalKarol** [comment]
@ad-m Ok, widzę że sdk się już przebudowało, musisz teraz tylko front przebudować.

**Comment by MichalKarol** [comment]
@ad-m Sry, z rana mam problem z czytaniem, widzę że już przebudowałeś. Mógłbyś dodać dostęp dla userów spoza organizacji, żebym mógł przetestować?

**Comment by ad-m** [comment]
Obecnie dostęp nie jest ograniczony.  Błąd jest na żądaniu `UsersExchange`.

**Comment by MichalKarol** [comment]
Dostęp jest obecnie tylko dla kont z organizacji. Przynajmniej taki błąd dostaję. Co do błędu w requeście zobacz czy idą paramsy w requeście do user exchange. Dodatkowo można zobaczyć czy update yarn.locka może pomóc.

**Comment by ad-m** [comment]
Faktycznie, ograniczone na poziomie Google, ale nie widzę w jakim miejscu.

**Comment by MichalKarol** [comment]
Ekran akceptacji OAuth w API Console?

**Comment by MichalKarol** [comment]
@ad-m Obstawiam że to naprawi: https://github.com/watchdogpolska/small_eod/pull/937

**Comment by MichalKarol** [comment]
Dlatego nie jestem fanem yarn.locka :P

**Comment by ad-m** [comment]
Naprawione w zakreesie uwierzytelniania dla @siecobywatelska.pl. 

@AgnieszkaZdanowicz skasuj cookies i powinnaś już móc korzystać z aplikacji. Nie ma tam danych z środowiska DEMO jeszcze, bo problem z wolnym czasem ładowania w weekend zajął mi więcej niż spodziewałem się, ale dziś wieczorem chce do tego usiąść.

**Comment by ad-m** [comment]
> Ekran akceptacji OAuth w API Console?

W tym rzecz, że w tym miejscu taka informacja nie jest widoczna:
![image](https://user-images.githubusercontent.com/3618479/117771052-fc401100-b235-11eb-9b4e-900190c89cd4.png)

**Comment by ad-m** [comment]
Będę mógł rozwiązać problem dopiero wieczorem. @mrbojko utworzysz tymczasowo konto dla @MichalKarol jako wolontariusza? Po rozwiązaniu problemu z zakresem dostępu naprawimy to, ale przydatne byłoby na wieczorny status.

**Comment by ad-m** [comment]
@MichalKarol , naprawione. Klucz API musiałem stworzyc od nowa, bo nie działa edycja, chociaż widać zedytowane. 

@mrbojko konto @siecobywatelska.pl dla @MichalKarol  nie jest już więcej wymagane.
