### ISSUE TITLE
integracja z Google w celu uwierzytelniania

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small_eod#97]

**Comment by ad-m** [comment]
django-rest-auth?

**Comment by ad-m** [comment]
Heroku ma dobrze wyjaśnione flow: https://devcenter.heroku.com/articles/oauth#oauth-flow 
Można je zaimplementować naprawdę w kilku linijkach kodu: https://github.com/ad-m/tsbk-auth/blob/master/index.js#L75-L99
Potrzebujemy przez OAuth uzyskać prawo do uzyskania w imieniu użytkownika jego profilu, co oznacza dla nas zalogowanie.
Jak już protokół jest zrozumiały to jest kilka bibliotek dla django-rest-framework, który implementuje to, więc potrzebujemy wybrać którąś ( https://www.django-rest-framework.org/api-guide/authentication/#third-party-packages ).

**Comment by ad-m** [comment]
Kluczowe do powyższego jst skuteczne udokumentowanie tych endpointów w naszej dokumentacji API.

@matiuszka , czy masz wszystko konieczne do zagadnienia?

**Comment by matiuszka** [comment]
Wydaje mi się, że wszystko co potrzebne mam. Zacznę od przeczytania wszystkich linków.

**Comment by magul** [comment]
Cześć @matiuszka, chciałbym spytać o status tego zadania? Miałeś okazję nad nim przysiąść?

Z góry dzięki za info!

**Comment by matiuszka** [comment]
Hej @magul, z całym zamieszaniem z koronawirusem zapomniałem o projekcie.
Poza reasearchem nie robiłem nic w temacie. Przysiądę dzisiaj i jutro nad tym. Powinno się udać.

Potrzebujesz tego issue do jakiś dalszych zadań ? Czy chciałbyś się tym zająć ?

**Comment by ad-m** [comment]
Ja rozważałem przejęcie tego zagadnienia jutro. Jakby co - cały dzień jestem przed komputerem, więc na pytania mogę odpowiedzieć.

**Comment by matiuszka** [comment]
W zasadzie udało się dodać to w paru linijkach ale nie wiem jak przetestować to w pełnej krasie.
Mianowicie chodzi mi o to, że endpoint /api/auth/login/google-oauth2/ przekierowuje na stronę autoryzacji ale parametr _redirect_url_ jest nie prawidłowy(http://backend/api/auth/complete/google-oauth2/) z racji tego, że wszystko jest lokalnie.

Jedyne co udało mi się potwierdzić to _convert_token_ przy google tokenie z OAuth 2.0 Playground. Tak jak jest to opisane tu:
https://github.com/RealmTeam/django-rest-framework-social-oauth2#google-example

**Comment by magul** [comment]
@matiuszka możesz to wrzucić na pull request? to zobaczymy pewnie wspólnie co możemy dalej z tym zrobić.

**Comment by matiuszka** [comment]
PR: https://github.com/watchdogpolska/small_eod/pull/286

Aby w pełni przetestować będzie wymagane by stworzyć aplikację w serwisie https://console.developers.google.com/apis/credentials.

Dodatkowo testy z autentykacją dla Collections zepsułem :) rzucę na to okiem.

**Comment by ad-m** [comment]
@matiuszka , masz możliwość i chęć w przyszłą środę o godzinie 18 spotkać się online i zaplanować prace? 

W tym czasie spotyka się front-end team, który zaczyna się kształtować dzięki [Code For Poznan](https://codeforpoznan.pl), więc może to ułatwic komunikacje.

Zepsułeś testy, które wykorzystują ```test_authorize_with_token```. To jest alternatywna forma uwierzytelniania w celu autoryzacji dostępu do kolekcji, co było przedmiotem #113.

**Comment by matiuszka** [comment]
@ad-m jasne, chętnie wezmę udział :)

Co do testów to już właśnie sobie oglądam kod i testy. Jestem dobrej myśli.

**Comment by matiuszka** [comment]
@ad-m Przejrzałem zmiany z #300. Zdecydowanie Twoje rozwiązanie jest lepsze. Myślę, że ma można zamknąć #286. Czego brakuje by zamknąć ten temat ?

**Comment by ad-m** [comment]
W ramach #300 mamy wciąż problem z autoryzacją kolekcji, bo jest tam specyficzny mechanizm autoryzacji. Zacząłem pracować nad uproszczonym sposobem uwierzytelniania, bo nie byłem w stanie w prosty sposób prześledzić dlaczego autoryzacja nie powodzi się. Przechodzenie przez kilka warstw bibliotek wokół OAuth nie ułatwiała tego.

Nie mniej, front-end startując z brancha #300 może już pracować, bo jest to w pełni funkcjonalne.

**Comment by kuskoman** [comment]
Trochę odkopuję, ale czy zakładanie uzyskania imienia użytkownika za zalogowanie nie jest trochę na wyrost? OAuth nie pozwala zweryfikować tożsamości, dopiero OpenID Connect zawiera elementy pozwalające na stwierdzenie tożsamości posiadacza tokenu

**Comment by ad-m** [comment]
OAuth nie definiuje, ale pozwala stwierdzić tożsamość posiadacza tokenu.

**Comment by ad-m** [comment]
Zagadnienie zostało wykonane w zakresie front-endu. Teraz potrzebujmy to ładnie zintegrować po stronie front-endu.
